### ISSUE TITLE
Are Subscriptions Possible Using This Library? How?

### ISSUE THREAD

**Issue by vicatcu** [Enngage/ngx-paypal#10]
Is it possible to create a subscription / recurring payment Button / workflow using this library (i.e. using PayPal's checkout.js)? And if so, can you give me a nudge in the right direction on how to configure `<ngx-paypal>` to do it? I can't seem to figure it out from PayPal's developer docs.

I mean I've found https://developer.paypal.com/docs/api/payments.billing-agreements/v1/
... but this seems like using straight REST API calls to create and activate a subscription, rather than delegating to PayPal to collect payment information an so forth. Am I missing something?

**Comment by Enngage** [comment]
Hi! Sorry for late response, I've been away. To be honoest, I'm not that much familiar with paypal's API other than what I've implemented for my needs. What you sent seems like it should be implementable as they have Node SDK which does the agreements. 

Were you able to find any details in the meantime that would help in implementing this?

**Comment by vicatcu** [comment]
No worries, I haven't given it much attention since posting this issue.

**Comment by Enngage** [comment]
Don't know if their Node SDK works in browser as well, but if you need that, I would likely recommend using their Node SDK directly - https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/create.js 

Not sure if this is something that would be worth 'recreating' if they support it OOTB.

**Comment by michaelkariv** [comment]
Hi all, any update on that?

**Comment by Mustahsan1** [comment]
here's a nice example how to acheive this with ngx-paypal: https://stackoverflow.com/a/66379968/9722122
