### ISSUE TITLE
Getting Compile Error 

### ISSUE THREAD

**Issue by nrogers805** [Enngage/ngx-paypal#108]
ERROR in node_modules/ngx-paypal/lib/components/paypal.component.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by mystery-man** [comment]
I updated my angular version and this issue got fixed. Update to Angular 9

**Comment by codemx** [comment]
I got the same issue and when I updated to Angular 9, I got errors in other places (I m using a template which is written for angular 7)
Is there any way of sort above issue without upgrading to angular 9
Or to avoid above issue can I install angular 7 compatible version of this package ? (I tried with installing version 4.0.0 and it also got failed.

**Comment by flaviox83** [comment]
`npm install ngx-paypal@5.0.0 --save`
works for my angular 7 project
