### ISSUE TITLE
Problem using intent of authorize

### ISSUE THREAD

**Issue by mmedic** [Enngage/ngx-paypal#109]
I am using order creation on the server with intent to authorize and later also capture the payment on the server. When using that intent I get the following error: Expected intent from order api call to be capture, got authorize. It seems to work ok in Sandbox but in production mode it fails.

**Comment by mmedic** [comment]
For other looking for a solution, configure advanced to specify the intent:
```
 this.payPalConfig = {
            currency: 'USD',
            clientId: environment.paypal.clientKey,
            advanced: {
              extraQueryParams: [{name: 'intent', value: 'authorize' }]  
            },
```

**Comment by ell360** [comment]
I am also trying to use intent... did you ever figure out a way to get the authorization ID?

**Comment by mmedic** [comment]
> I am also trying to use intent... did you ever figure out a way to get the authorization ID?

See my comment directly above. That is how I fixed it.
