### ISSUE TITLE
Property 'intent' does not exist on type 'IPayPalCancelPayment'

### ISSUE THREAD

**Issue by shubhamdixit863** [Enngage/ngx-paypal#11]
I am getting this error during payment cancel ,inspite your model having the same fields !!

**Comment by Enngage** [comment]
This is very brief description, though the error is correct. `intent` does not exist in `IPayPalCancelPayment`, it does however in `IPayPalCancelPaymentData ` - see https://github.com/Enngage/ngx-paypal/blob/master/projects/ngx-paypal-lib/src/lib/models/paypal-models.ts#L101

Closing for now. If there is some issue, feel free to reopen.
