### ISSUE TITLE
Missing property disable-card

### ISSUE THREAD

**Issue by DomEscobar** [Enngage/ngx-paypal#112]
Can you implement this option property please.
https://developer.paypal.com/docs/checkout/reference/customize-sdk/#disable-card

Thank you 👍

**Comment by DomEscobar** [comment]
Workaround (type to any) : 

`   
funding: {
        allowed: ['PayPal'],
        disallowed: []
      },
`

**Comment by anhurtado** [comment]
Hi @DomEscobar with that way you can disable card or paypal payment?

**Comment by JasonMacfarlane** [comment]
You can also do this with the **advanced** property in the PayPal config. Something like this:

`advanced: { extraQueryParams: [ { name: 'disable-funding', value: 'card' } ] }`

If you want to disable cards, change the name to **disable-card** and value to the card(s) you want to disable.
