### ISSUE TITLE
Creating orders on server: Reference Id?

### ISSUE THREAD

**Issue by kombasltd** [Enngage/ngx-paypal#115]
Hi,

I have a logical problem at the moment. I implemented the PayPal example to create an order on the server, which works with the example given for .NET by PayPal.

But I need to send some kind of Id from the client to the server to tell the API WHICH order or Cart should be used to create the order.

```
createOrderOnServer: (data) => fetch('/my-server/create-paypal-transaction')
                .then((res) => res.json())
                .then((order) => order.orderID),
```
Where do I put some kind of Id to the API call? What am I missing?

**Comment by Enngage** [comment]
Take a look at PayPal's flow described at https://developer.paypal.com/docs/archive/checkout/how-to/server-integration/#how-a-server-integration-works
