### ISSUE TITLE
Payment amount value will not change 

### ISSUE THREAD

**Issue by stevemalko** [Enngage/ngx-paypal#118]
have been testing the paypal module on an item costing $.01....worked successfully
started testing it on an item costing $5....but it still shows $.01
changed the code around, started hard coding values, still shows $.01 on the paypal confirmation page

any ideas? feels like something is cached

**Comment by Enngage** [comment]
You have to reinitialize entire config for change to come into effect. Its working in the demo site. You can check the implementation at https://github.com/Enngage/ngx-paypal/blob/master/demo/app/pages/home.component.ts#L128

**Comment by stevemalko** [comment]
Hi @Enngage maybe I didnt explain myself clearly, I have implemented the code in its barest form, exactly as the instructions say, hard coding all values ($21.01)....when I click the gold paypal button, it charges me only 0.01......it seems that onit, its not reading any of my parameters

http://stevemalko.com/angular
