### ISSUE TITLE
Document is ready and element #ngx-captcha-id-1589609413145 does not exist

### ISSUE THREAD

**Issue by anhurtado** [Enngage/ngx-paypal#119]
I received this error and i do not understand what's happens, any idea about that

`OnError Error: Document is ready and element #ngx-captcha-id-1589609413145 does not exist
    at js?client-id=AV1YroINHBYa0DTU7BO6n949KTCzXWTxExhepXrWnSOKQ8S2NDZ9jsuWBSqZkGcAlhZwqhwEemF4TSfR&currency=USD&commit=true:2
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Zone.runTask (zone-evergreen.js:168)
    at invokeTask (zone-evergreen.js:465)
    at ZoneTask.invoke (zone-evergreen.js:454)
    at timer (zone-evergreen.js:2`

**Comment by Enngage** [comment]
This is probably some timing issue - depends how you are creating your components / paypal and if you are modifying DOM in some way. 

It's not really possible to tell what is going on just by this exception. I would recommend setting up paypal in some of your "blank" page if you are unsure and once it works, bring it to your workflow step by step. 

+ You can always check the demo implementation at https://github.com/Enngage/ngx-paypal/tree/master/demo

**Comment by logan-jobzmall** [comment]
@Enngage I am getting this same error when trying to have 3 different instances of the component within an `*ngIf`, whilst using the same configuration for all of them. I am trying to find a way to either do a setTimeout() or something - but not seeing much success.

**Comment by Emanuel1130** [comment]
@Enngage Getting same problem

**Comment by RudyAlmeida** [comment]
Had the same isue, in my case it was inside a modal, solved the problem calling initConfig() only when modal as called.
