### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by anhurtado** [Enngage/ngx-paypal#120]
Hi @Enngage when my code compile the terminal show me the next message:

`ERROR in node_modules/ngx-paypal/lib/components/paypal.component.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27     set payPalButtonContainer(content: ElementRef);
           ~~~~~~~~~~~~~~~~~~~~~`

Despite everything it works for me, although I would like to solve that detail

**Comment by Enngage** [comment]
@anhurtado, you are probably using outdated typescript version. I would also recommend deleting your node_modules and performing a clean install just in case. -> see https://github.com/storybookjs/storybook/issues/9463

**Comment by anhurtado** [comment]
@anhurtado i tried with the clean installation and not working. i have typescript v3.5.3

**Comment by Enngage** [comment]
Thats a bit older version. Why are you not using the latest compatible with
Angular 9 which is Typescript *3.8.3 ?*

**Comment by anhurtado** [comment]
@Enngage I'm development the project right now, i will try to update angular project soon, show you the results. I hope works!
