### ISSUE TITLE
`ngx-paypal"' has no exported member 'PayPalEnvironment'`

### ISSUE THREAD

**Issue by manishaghuge** [Enngage/ngx-paypal#121]
`ngx-paypal"' has no exported member 'PayPalEnvironment'`
`ngx-paypal"' has no exported member 'PayPalIntegrationType'`

Went to the node_modules folder and searched within there for these models and couldn't find them. Is there something wrong with the repo?

_Originally posted by @botoxparty in https://github.com/Enngage/ngx-paypal/issues/39#issuecomment-469074551_

**Comment by Enngage** [comment]
These properties were long removed and are no longer necessary.
