### ISSUE TITLE
Handle http errors from paypal

### ISSUE THREAD

**Issue by marcelhader** [Enngage/ngx-paypal#126]
At the moment the sandbox of paypal has some issues and provided a 500 when the checkout is initialed. (/v2/checkout/orders returned status: 500) 

Is it possible, that you foward this error to onError at the paypalConfig or add a new method onHttpError that we can handle these errors and show the user an dialog that the paypal service is not available.

**Comment by Enngage** [comment]
There already is `onError` callback property which contains original errors.
