### ISSUE TITLE
'createOrder' does not exist in type 'IPayPalConfig'.ts(2322)

### ISSUE THREAD

**Issue by guntercn** [Enngage/ngx-paypal#130]
HI.

error

Type '{ currency: any; clientId: string; createOrder: (data: any) => ICreateOrderRequest; advanced: { commit: "true"; }; style: { label: "paypal"; layout: "vertical"; }; onApprove: (data: IOnApproveCallbackData, actions: any) => void; onClientAuthorization: (data: IClientAuthorizeCallbackData) => void; onCancel: (data: IC...' is not assignable to type 'IPayPalConfig'.
  Object literal may only specify known properties, and 'createOrder' does not exist in type 'IPayPalConfig'.ts(2322)

On 

 payPalConfig = {
              currency: '$',
              clientId: 'API_CODE',                  
             createOrder: (data) => < ICreateOrderRequest > {
                  intent: 'CAPTURE',
...................

Thanks!

**Comment by Woomber** [comment]
Hi, this is because in this library, `createOrder` is replaced by `createOrderOnClient` and `createOrderOnServer`, depending on what you need to do.  So you should use one of them instead! 

**Example**:

```
 this.payPalConfig = {
            currency: 'USD',
            clientId: 'API_CODE',
            createOrderOnClient: (data) => < ICreateOrderRequest > {
                intent: 'CAPTURE',
                ...
            },
            ...
        };
    }
```
