### ISSUE TITLE
Removing Credit or Debit action button

### ISSUE THREAD

**Issue by devmanateam** [Enngage/ngx-paypal#134]
Hi, support, how are you. i am very happy to use this module.
i have a problem in using this module.
my client is requesting to remove Credit or Debit button in his app.
is there any solution to remove the button?

**Comment by Enngage** [comment]
I don't know, you have to see official PayPal API https://developer.paypal.com/docs/checkout/reference/customize-sdk/ and set appropriate properties when initializing paypal component.

**Comment by devmanateam** [comment]
but i am using ngx-paypal module, not javascript paypal-sdk.

**Comment by Enngage** [comment]
Did you read the readme? Its right at the top:

```
This Angular library is based on PayPal's Javascript SDK. It does not support each and every feature of the JavaScript SDK so feel free to submit issues or PRs.
```

**Comment by devmanateam** [comment]
hmmm, so should i give up to use ngx-paypal to solve my facing problem?

**Comment by Enngage** [comment]
If you don't use `ngx-paypal` you will have to use PayPal's Javascript SDK anyways so its really up to you. You cannot use PayPal without PayPal's SDKs... This library only helps you use the SDK in a more friendly and easier way, but its dependant on PayPal.

**Comment by devmanateam** [comment]
Thanks for your help. i really like to use this, but i will try to use javascript paypal sdk to solve my problem.
Thanks again.

**Comment by EinarasGar** [comment]
In case somebody is looking for a solution to this problem:

In your PayPalConfig object, add this field.
`advanced: {
        extraQueryParams: [
          { name: "disable-funding", value:"credit,card"}
        ]
      } ,`

Available options are here: https://developer.paypal.com/docs/checkout/reference/customize-sdk/#disable-funding
