### ISSUE TITLE
Error compiling module for Angular 9

### ISSUE THREAD

**Issue by iMustafa** [Enngage/ngx-paypal#138]
ERROR in node_modules/ngx-paypal/lib/ngx-paypal.module.d.ts:6:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-paypal) which declares NgxPayPalModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

Package.json
```
"@angular-ru/ngx-i18n-combine": "^1.1.0",
"@angular/animations": "~9.1.0",
"@angular/cdk": "^9.2.0",
"@angular/common": "~9.1.0",
"@angular/compiler": "~9.1.0",
"@angular/core": "~9.1.0",
"@angular/fire": "^6.0.0",
"@angular/flex-layout": "^9.0.0-beta.29",
"@angular/forms": "~9.1.0",
"@angular/material": "^9.2.0",
"@angular/platform-browser": "~9.1.0",
"@angular/platform-browser-dynamic": "~9.1.0",
"@angular/platform-server": "~9.1.0",
"@angular/router": "~9.1.0",
"ngx-paypal": "^6.2.0"
```

**Comment by Enngage** [comment]
Delete node_modules and reinstall all packages.

**Comment by iMustafa** [comment]
I already tried that before submitting the issue, tried again didn't work either.
Getting the same error

**Comment by andrevabo** [comment]
Same error here. Deleting node_modules and reinstalling made no difference at all. 

ERROR in node_modules/ngx-paypal/lib/ngx-paypal.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of PaymentModule, but could not be resolved to an NgModule class.
    
This likely means that the library (ngx-paypal) which declares NgxPayPalModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.


My package.json
```
    "@angular/animations": "^9.1.4",
    "@angular/cdk": "^9.2.1",
    "@angular/common": "^9.1.4",
    "@angular/compiler": "^9.1.4",
    "@angular/core": "^9.1.4",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.1.4",
    "@angular/material": "^9.2.1",
    "@angular/platform-browser": "^9.1.4",
    "@angular/platform-browser-dynamic": "^9.1.4",
    "@angular/platform-server": "^9.1.4",
    "@angular/router": "^9.1.4",
    "ngx-paypal": "^6.2.0",
```

**Comment by remorr25** [comment]
Any solution for this issue?

**Comment by edwingr93** [comment]
hay alguna soluccion ??
