### ISSUE TITLE
interface IPayPalButtonStyle missing Layout : horizontal & vertical

### ISSUE THREAD

**Issue by vinayak519** [Enngage/ngx-paypal#14]
Building app with Angular 6 I noticed the layout is missing in button styles: 
added in paypal-model.ts and works well, 

it outputs below error: 
error TS2345: Argument of type '{ commit: true; client: { sandbox: string; }; button: { label: "paypal"; layout: string; size: "m...' is not assignable to parameter of type '{ onError?: (err: any) => void; onCancel?: (data: IPayPalCancelPayment, actions: any) => void; pa...'.
  Types of property 'button' are incompatible.
    Type '{ label: "paypal"; layout: string; size: "medium"; shape: "rect"; color: "gold"; }' is not assignable to type 'IPayPalButtonStyle'.
      Object literal may only specify known properties, and 'layout' does not exist in type 'IPayPalButtonStyle'.

**Comment by Enngage** [comment]
What 'layout' are you referring to? Can you send a link to PayPal's documentation?

**Comment by Enngage** [comment]
Will be in next release
