### ISSUE TITLE
information

### ISSUE THREAD

**Issue by johnfra797** [Enngage/ngx-paypal#15]
I have this error when rendering several buttons

paypal checkout integration script with same version (4.0.211) already loaded on page

**Comment by Enngage** [comment]
So you are basically using multiple instances of ngx-paypal, right? I'll have a look if this can be fixed easily.

**Comment by Enngage** [comment]
Implemented in latest release, please try upgrading.

**Comment by Enngage** [comment]
Released in `3.1.0`
