### ISSUE TITLE
Issue in using the Ngx Paypal package

### ISSUE THREAD

**Issue by rwfermin** [Enngage/ngx-paypal#150]
HI all, I'm quite new to Angular (newer version) and I was asked to implement the Paypal payment mode in our project.
I searched for available implementation online and stumbled upon this particular implementation.

I just followed whatever is on docs: https://enngage.github.io/ngx-paypal/
which is same on the Github page

The structure looks like this:

Payment parent component will handle all payment modes including Paypal, etc.

Parent (Payment Parent)
- Paypal (Payment child)
- Other Payment methods (Payment child)

So on **payment-parent** module file

`import { NgxPayPalModule } from 'ngx-paypal';
...
import { PaymentModePaypalComponent } from './payment-mode-paypal/payment-mode-paypal.component';

@NgModule({
  imports: [
    ...
    NgxPayPalModule,
  ],
})`

then the payment mode paypal component (child) will have the component and the template.
No module file found for all payment children.

So basically just followed whatever is on the docs above but my project is not loading because of this.
When i checked console:

`Uncaught TypeError: Class constructor ScriptService cannot be invoked without 'new'
    at Module../node_modules/ngx-paypal/__ivy_ngcc__/fesm2015/ngx-paypal.js (script.service.ts:52)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/components/checkout/payment-modes/payment-modes.module.ts (payment-modes.module.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/components/checkout/checkout.module.ts (checkout.module.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/components/components.module.ts (components.module.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app.module.ts (app.module.ts:1)
    at __webpack_require__ (bootstrap:79)`

If I checked those lines:
Is it pointing here:
`import { CommonModule } from '@angular/common';`

If I tried not importing into ngx-paypal into the module, sometimes it is loading, but the error looks like this:

`ERROR in src/app/components/checkout/payment-modes/payment-mode-paypal/payment-mode-paypal.component.html:8:3 - error NG8001: 'ngx-paypal' is not a known element:
    1. If 'ngx-paypal' is an Angular component, then verify that it is part of this module.
    2. If 'ngx-paypal' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    
    8   <ngx-paypal [config]="payPalConfig"></ngx-paypal>
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/components/checkout/payment-modes/payment-mode-paypal/payment-mode-paypal.component.ts:7:16
        7   templateUrl: './payment-mode-paypal.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component PaymentModePaypalComponent.
    src/app/components/checkout/payment-modes/payment-mode-paypal/payment-mode-paypal.component.html:8:15 - error NG8002: Can't bind to 'config' since it isn't a known property of 'ngx-paypal'.
    1. If 'ngx-paypal' is an Angular component and it has 'config' input, then verify that it is part of this module.
    2. If 'ngx-paypal' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
    
    8   <ngx-paypal [config]="payPalConfig"></ngx-paypal>
                    ~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/components/checkout/payment-modes/payment-mode-paypal/payment-mode-paypal.component.ts:7:16
        7   templateUrl: './payment-mode-paypal.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component PaymentModePaypalComponent.`

Any idea how to resolve these issues?

**Comment by Enngage** [comment]
You are probably incorrectly importing modules in your angular.. I would recommend that you look and study this - https://angular.io/guide/architecture-modules
