### ISSUE TITLE
How to use only PayPal button?

### ISSUE THREAD

**Issue by prettydev** [Enngage/ngx-paypal#154]
I want to remove "Pay Later" button and "Two easy ways to pay" label, and want to display only "PayPal" button. 
How to configure the modules for this purpose?
![image](https://user-images.githubusercontent.com/53688893/104613993-a61ee080-563c-11eb-9fed-90fbf3ad1436.png)
My current configuration is as following.
```
this.payPalConfig = {
      currency: 'USD',
      clientId: environment.paypalKey,
      advanced: {
        commit: 'true'
      },
      style: {
        label: 'paypal',
        layout: 'horizontal',
        size: 'small',
        shape: 'rect',
        color: 'silver',
      },
      createOrderOnClient: (data) => <ICreateOrderRequest>{},
      onApprove: (data, actions) => {},
      onClientAuthorization: (data) => {}
      onCancel: (data, actions) => {},
      onError: err => {},
      onClick: (data, actions) => {},
    };
```

**Comment by JRafael91** [comment]
https://developer.paypal.com/docs/checkout/reference/customize-sdk/#disable-funding
