### ISSUE TITLE
Unable to do validation with validation, onClick functions

### ISSUE THREAD

**Issue by chifis** [Enngage/ngx-paypal#16]
I'm trying to integrate paypal with your library. But i have a form, user have to fill before payment.

In official paypal documentation, they have provided couple of functions like validation, onClick.
https://developer.paypal.com/demo/checkout/#/pattern/validation

I'm not able to pass them in configuration object as they are not declared in model class. Can you please let me know if there is any work around for the same?

**Comment by Enngage** [comment]
I've implemented the handler and will include it in next release (likely Today). I wish this was documented somewhere as I've only found it in the example you mentioned and here https://developer.paypal.com/docs/checkout/best-practices/#performance-and-analytics 

If you know of anything missing, please let me know!

**Comment by Enngage** [comment]
Released in `3.1.0`

**Comment by chifis** [comment]
Hi @Enngage , Thank you for the update. I can now add handler for onClick event. 

But still there is no way to stop the action to go to paypal. Can you please add a validate callback, so we can store actions and call enable/disable to stop payment request like in this documentation.
https://developer.paypal.com/demo/checkout/#/pattern/validation

**Comment by chifis** [comment]
Hi @Engage , thank you will check and let you know.

**Comment by chifis** [comment]
Hi i just checked with the latest version. Now i'm able to stop the click action on PayPal button if form is invalid. Thank you :)

**Comment by Enngage** [comment]
Awesome, thanks for confirming!
