### ISSUE TITLE
Wrong api call for subscriptions

### ISSUE THREAD

**Issue by milantwog** [Enngage/ngx-paypal#161]
Currently, while testing subscriptions with sandbox, i get 404 error, because call to the API is wrong, instead of https://api-m.sandbox.paypal.com/v1/billing/subscriptions component is calling https://www.sandbox.paypal.com/v1/billing/subscriptions

**Comment by Enngage** [comment]
This library has no reference for either of your links. I believe it's PayPal who is generating this URL and I would assume they are correct as one seems to be triggered from mobile and the other is the default one.
