### ISSUE TITLE
How do I disable or hide Paypal buttons?

### ISSUE THREAD

**Issue by maxima120** [Enngage/ngx-paypal#164]
is there a property on ngx-paypal or the config that I can use to disable or hide the buttons? like `isEnabled` ? and if not - can you add it? I mean how do you deal with situation when order has been placed successfully and you want to avoid a over-active user to click Paypal button again..

**Comment by Enngage** [comment]
Why not use ngIf on the wrapper element? It doesnt make much sense for this
to be included in library.

**Comment by maxima120** [comment]
fair enough.. just thought you might have it in a property..
btw **setting config to null** also hides the component..
