### ISSUE TITLE
Cant use production

### ISSUE THREAD

**Issue by AdrenalineRP** [Enngage/ngx-paypal#169]
I'm able to use production paypal, i build in prod, use the prod client id but still uses sandbox.paypal.com.
what am i doing wrong?

**Comment by elcrostatina** [comment]
@AdrenalineRP in the payPalConfig you should to specify your production clientId, something like this:

```
payPalConfig = {
       clientId: 'YOUR_ID', // <-- HERE 
      advanced: {
        commit: 'true',
      },...
```

**Comment by derciesto** [comment]
@elcrostatina hi i update my paypal live client id but still request go to the sandbox 

![image](https://user-images.githubusercontent.com/90903226/154486554-00a87bec-cb0c-466e-b4ad-49776eb48e42.png)
error I facing 

please help me with that.

thanks in andvance.
