### ISSUE TITLE
Integrate Venmo

### ISSUE THREAD

**Issue by hampton1122** [Enngage/ngx-paypal#170]
Looking at documentation found here: https://developers.braintreepayments.com/guides/venmo/client-side/javascript/v3
There seems to be more control over Venmo with PayPal in the V3 SDK. Is it possible to update your library to work with v3?

Thanks for your consideration.

**Comment by Enngage** [comment]
Hi, 

Sorry, but I'm not planning on creating creating new sdk for braintree.
