### ISSUE TITLE
Set payee

### ISSUE THREAD

**Issue by RobertoGemo** [Enngage/ngx-paypal#175]
Hi,
I am trying to use this component in an Angular pwa where i need to send payments to different paypal users.
this is my config:
this.payPalConfig = {
      currency: 'EUR',
      clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      // tslint:disable-next-line: no-angle-bracket-type-assertion
      createOrderOnClient: (data: any) => <ICreateOrderRequest>{
        intent: 'CAPTURE',
        purchase_units: [{
          payee: {
            email_address: 'aaaaaa@aaaaaa.it'
          },
          amount: {
            currency_code: 'EUR',
            value: '0.01',
            breakdown: {
              item_total: {
                currency_code: 'EUR',
                value: '0.01'
              }
            }
          },
          items: [{
            name: 'Enterprise Subscription',
            quantity: '1',
            category: 'DIGITAL_GOODS',
            unit_amount: {
              currency_code: 'EUR',
              value: '0.01',
            },
          }]
        }]
      },
      advanced: {
        commit: 'true'
      },
      style: {
        label: 'paypal',
        layout: 'vertical'
      },
      onApprove: (data, actions) => {
        console.log('onApprove - transaction was approved, but not authorized', data, actions);
        actions.order.get().then(details => {
          console.log('onApprove - you can get full order details inside onApprove: ', details);
        });

      },
      onClientAuthorization: (data) => {
        console.log('onClientAuthorization - you should probably inform your server about completed transaction at this point', data);
        // this.showSuccess = true;
      },
      onCancel: (data, actions) => {
        console.log('OnCancel', data, actions);
        // this.showCancel = true;

      },
      onError: err => {
        console.log('OnError', err);
        // this.showError = true;
      },
      onClick: (data, actions) => {
        console.log('onClick', data, actions);
        // this.resetStatus();
      },
    };

if i remove the payee node the component works fine but if a specify the payee account i get an error saying that the merchant id does not match the email address.
i thougth that field should not be mandatory because only "business" accounts have one, am i right?

**Comment by Enngage** [comment]
@RobertoGemo Hey, this sort of "business" question is better suited for PayPal support. This library is only an abstraction layour on top of PayPal's API and I have no idea what rules PayPal follows. It is your responsibility as developer to send proper data to PayPal API.
