### ISSUE TITLE
content-security-policy

### ISSUE THREAD

**Issue by aylmercarson** [Enngage/ngx-paypal#176]
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' *****". Either the 'unsafe-inline' keyword, a hash ('sha256-xxxxxxx='), or a nonce ('nonce-...') is required to enable inline execution.

my client id is held server-side and retrieved when a user clicks the "paypal" button. 
i'm not willing to use "unsafe-inline" and can't see how to add a nonce or hash where it needs to be added. can anybody help please?

**Comment by Enngage** [comment]
I don't understand. This library is based on official PayPal's documentation (https://developer.paypal.com/docs/checkout/#try-the-buttons) and there is nothing insecure about exposing your client id. You should revisit your app and do it as PayPal recommends rather then solving non-existent issues.

**Comment by aylmercarson** [comment]
that was a tad rude. it was nothing to do with paypal, but it's ok, i fixed it. thanks for your help

**Comment by Enngage** [comment]
It's difficult to advice when so little information is given and when you don't provide e.g. samples of how you use this library and how it relates to PayPal. I'm just being direct. What was the problem though? Was it something with PayPal / this library?

**Comment by aylmercarson** [comment]
both, in a way. standard paypal stuff suggests an inline call to their script:
  <script src="https://www.paypal.com/sdk/js?client-id=mycid"></script>

good practice suggests disallowing inline scripts due to (real) security concerns. 
therefore, my csp (configured in in startup.cs) disallows inline script references.
i was hoping your component would have a way of referencing the script, maybe using an onload event for example, the way you can do in angular.
however, my "fix" was, for the time being, smply to allow inline-script in my csp. but this is not good, so i will be looking at a way of adressing it. tbh i'm close to dumping paypal as a payment vehicle altogether as it's a bit of a moving target. and much as i appreciate your work with this component here, it moves at a slightly slower pace that the angular framework itself and so angular updates are not easily dealt with. i have moved to angular 12 and consequently, for the time being at least, this component is out of reach.
