### ISSUE TITLE
Button style size : "small" not working 

### ISSUE THREAD

**Issue by parth2799** [Enngage/ngx-paypal#179]
Hello

Use a different type of size in the button but its not reflected in the screen 

example :
style: {
        label: 'paypal',
        layout: 'horizontal',
        tagline: false,
        shape : 'pill',
        size : "small"
      },

**Comment by Enngage** [comment]
Hi,

PayPal seems to have removed this configuration option from their API. They say that the buttons adjust based on their parents container.
