### ISSUE TITLE
Configure PayPal Payment Experience

### ISSUE THREAD

**Issue by vladardelean** [Enngage/ngx-paypal#18]
It should be possible to configure the PayPal Payment Experience as described [here](https://developer.paypal.com/docs/api/payment-experience/v1/#definition-presentation).

The following should be supported:
- Hide the shipping address field
- Replace the business account displayed on the page with a different value
- Replace the PayPal logo with own brand image
- Show the checkout page in a different locale

**Comment by Enngage** [comment]
Thank you! I will have a look.

**Comment by Enngage** [comment]
Closing as merged. Thanks again!

**Comment by dcasbonne** [comment]
Sorry to re-open an old issue, i wasn't sure if I comment here or open a new one !
I'm not able to change the locale or set my own image. I don't know what am I doing wrong...

`experience: {
        noShipping: true,
        brandName: 'Espace client SIGA',
        logoImage : 'url_complete.png',
        localeCode : 'CA'
      },`

Thank you for your help !

**Comment by mautrok** [comment]
I looked at eh source but i didn't fine the experience field, in what class are they now? Because it seems that it has been removed from:

paypal-models.ts

Thank for your help
