### ISSUE TITLE
Angular 12 Support

### ISSUE THREAD

**Issue by classicPintus** [Enngage/ngx-paypal#180]
I'm trying to update my project to Angular 12 but ngx-paypal is preventing me to update the project.

The error is the following
```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.1.0" from ngx-paypal@7.0.0
npm ERR! node_modules/ngx-paypal
npm ERR!   ngx-paypal@"7.x" from the root project
```

Is there the chance to fix it?

**Comment by Enngage** [comment]
There is something wrong with your environment. Try clearing out node_modules and/or deleting package-lock.json and reinstalling all modules from scratch. You might also need to clear npm cache.

**Comment by classicPintus** [comment]
I disagree.

I've just run the following commands

```
npm cache clean --force
ng new my-project (accepting routing and css)
cd my-project
npm install
npm install ngx-paypal --save
```

And the output is the following

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: angular-dodici-prova@0.0.0
npm ERR! Found: @angular/common@12.1.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.1.0" from ngx-paypal@7.0.0
npm ERR! node_modules/ngx-paypal
npm ERR!   ngx-paypal@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I'm using npm v7.6.2 and node v14.16.0

**Comment by Enngage** [comment]
You arr free to disagree, but thousands people are using it angular 12 just
fine so ask yourself, is something wrong with the thousands of people or
your environment? :)

Not trying to be rude, just saying it really does work in angular 12 just
fine.

Have you tried deleting those node_modules and package lock?

**Comment by Enngage** [comment]
I will release an update with Angular 12 peer deps though, it's about time
I guess ;)
