### ISSUE TITLE
Angular 12 please

### ISSUE THREAD

**Issue by maxima120** [Enngage/ngx-paypal#182]
NPM throws bunch of errors if you try to install ngx-paypal with Angular 12. I had to override it with `--force`. It seems to be working but would be a lot nicer if there wasnt Angular 11 dependency.. I dont know if it is hard to do but would appreciate if you could sort it out.

**Comment by Krivobarac** [comment]
Can we expect @12 soon :)

**Comment by aylmercarson** [comment]
there is now a pr for this :)

**Comment by maxima120** [comment]
Hope it is approved soon..

**Comment by Enngage** [comment]
Yeah, I hope to make it next week

**Comment by Enngage** [comment]
Released

**Comment by maxima120** [comment]
thank you!
