### ISSUE TITLE
Paypal API functioning problems via sandbox

### ISSUE THREAD

**Issue by Eleonor6** [Enngage/ngx-paypal#186]
I am using these APIs for a university project and I am **no longer able to carry out the tests** because as soon as I click on the Paypal button the window opens for a few seconds and then **closes automatically** without letting me enter the various data.
Can it be solved?? Thanks in advance

**Comment by ajithK24** [comment]
> I am using these APIs for a university project and I am **no longer able to carry out the tests** because as soon as I click on the Paypal button the window opens for a few seconds and then **closes automatically** without letting me enter the various data.
> Can it be solved?? Thanks in advance

which paypal version you use?
