### ISSUE TITLE
The component stopped to work

### ISSUE THREAD

**Issue by maxima120** [Enngage/ngx-paypal#187]
I havent tested Paypal functionality for couple weeks. The version in this app is 7.0.0
Today it didnt work. The prod website is still OK (code base a month old but I am sure the same version of ngx-paypal).

I tried sb and other Client IDs including prod - same effect.

It prints errors in console: 
![image](https://user-images.githubusercontent.com/10121753/129483194-a57ef20b-1165-4efd-8830-07c8a836ee5b.png)

Anyone had this issue? Could it be due to Paypal recent policies changes? Any idea how to investigate? 

**EDIT:** I rolled back the whole app to end of July when Paypal worked for sure. And it didnt work either. So I realised it must be the browsers (as I normally use Edge and a little Chrome). So I **tested on Firefox and it worked.** I tried the latest code and it is still working with Firefox but neither with Edge nor Chrome).

*Edge: Version 92.0.902.73 (Official build) (64-bit)
Chrome: Version 92.0.4515.131 (Official Build) (64-bit)
Firefox: Version 90.0.2 (64-bit)*

**EDIT2:** actual issue is that the callback `createOrderOnServer` is not called at all, the code hasnt changed for months, the controller never hit its breakpoint, there is no attempt to call `account/payment` on button click in Fiddler, nothing at all. only call to paypal which apparently times out after 10 sec:
```
      createOrderOnServer: (data) =>
        this.http.post<IPaymentResponse>(`${this.baseUrl}account/payment`, this.selectedProductId)
          .toPromise()
          .then((res) => {
            return res.order;
          })
          .then((order) => {
            return order.id;
          })
          .catch(error => {
            console.error('Server create payment ERROR', error);
            return null;
          }),
```

**Comment by ajithK24** [comment]
> I havent tested Paypal functionality for couple weeks. The version in this app is 7.0.0
> Today it didnt work. The prod website is still OK (code base a month old but I am sure the same version of ngx-paypal).
> 
> I tried sb and other Client IDs including prod - same effect.
> 
> It prints errors in console:
> ![image](https://user-images.githubusercontent.com/10121753/129483194-a57ef20b-1165-4efd-8830-07c8a836ee5b.png)
> 
> Anyone had this issue? Could it be due to Paypal recent policies changes? Any idea how to investigate?
> 
> **EDIT:** I rolled back the whole app to end of July when Paypal worked for sure. And it didnt work either. So I realised it must be the browsers (as I normally use Edge and a little Chrome). So I **tested on Firefox and it worked.** I tried the latest code and it is still working with Firefox but neither with Edge nor Chrome).
> 
> _Edge: Version 92.0.902.73 (Official build) (64-bit) Chrome: Version 92.0.4515.131 (Official Build) (64-bit) Firefox: Version 90.0.2 (64-bit)_
> 
> **EDIT2:** actual issue is that the callback `createOrderOnServer` is not called at all, the code hasnt changed for months, the controller never hit its breakpoint, there is no attempt to call `account/payment` on button click in Fiddler, nothing at all. only call to paypal which apparently times out after 10 sec:
> 
> ```
>       createOrderOnServer: (data) =>
>         this.http.post<IPaymentResponse>(`${this.baseUrl}account/payment`, this.selectedProductId)
>           .toPromise()
>           .then((res) => {
>             return res.order;
>           })
>           .then((order) => {
>             return order.id;
>           })
>           .catch(error => {
>             console.error('Server create payment ERROR', error);
>             return null;
>           }),
> ```
Face the same issue 
I Updated the ngx paypal to 8.0.0 now it is working fine

**Comment by maxima120** [comment]
Do you run it on Angular 12?

**Comment by ajithK24** [comment]
> Do you run it on Angular 12?

I do it in Angular 10

**Comment by maxima120** [comment]
I tried to upgrade it didnt work.. Tried today again - nope, same thing.. But I have Angular 11:
```
  "dependencies": {
    "@angular/animations": "11.2.14",
    "@angular/common": "11.2.14",
    "@angular/compiler": "11.2.14",
    "@angular/core": "11.2.14",
    "@angular/forms": "11.2.14",
    "@angular/platform-browser": "11.2.14",
    "@angular/platform-browser-dynamic": "11.2.14",
    "@angular/platform-server": "11.2.14",
    "@angular/router": "11.2.14",
    "@microsoft/signalr": "^5.0.9",
    "@popperjs/core": "^2.9.2",
    "bootstrap": "^4.6.0",
    "core-js": "^3.8.3",
    "devextreme": "21.1.5",
    "devextreme-angular": "21.1.5",
    "jquery": "^3.5.1",
    "ngx-paypal": "^8.0.0",
    "oidc-client": "^1.11.3",
    "rxjs": "^6.6.6",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1102.14",
    "@angular/cli": "^11.2.14",
    "@angular/compiler-cli": "^11.2.14",
    "@angular/language-service": "^11.2.14",
    "@types/node": "^14.14.28",
    "ini": "^1.3.7",
    "typescript": "4.1.6"
  },
  "optionalDependencies": {
    "eslint": "^7.27.0",
    "ts-node": "~8.4.1"
  }

```

**Comment by maxima120** [comment]
OK apparently it doesnt work only if VS is attached (i.e. while I am debugging). If I run a standalone browser Paypal works.. So basically its not working in a development process. It is a big of good news. But all the same - this needs to be fixed..

**Comment by Enngage** [comment]
If you can tell me how to fix it, I can try, but otherwise I dont really
think this is a problem with this library. Rather it seems like some sort
of limitation of paypal API.

**Comment by maxima120** [comment]
yeah if I knew :) ok lets put it on ice for now..
*just to stress again - it was working fine for a long time and stopped about a month or two ago*

**Comment by maxima120** [comment]
Bingo! I found the problem! its Visual Studio JS debugger.

If you use new JS debugger (which is I dont know how to call but from what I know it is sorta experimental feature that they are pushing to replace *old debugger* - whatever that means :) ) then the ngx-paypal and/or paypal SDK stop to work:

![image](https://user-images.githubusercontent.com/10121753/130680110-8eb15035-8a9e-4739-8409-523be42c0c66.png)

**Comment by Enngage** [comment]
Well, in that case its probably some change on PayPal side because I havent
really been making any changes here :) I only updated peer deps for Angular
12 if I remember correctly.

**Comment by maxima120** [comment]
Just to clarify - if you **uncheck** those checkboxes - you can use ngx-paypal while debugging from Visual Studio. If they are checked - you are out of luck..

**Comment by pkenny1** [comment]
The same issue is occurring in VS Code. Is there an equivalent set of settings to turn off in code to get around this issue?

**Comment by ferryhtw** [comment]
I also got same issues with VS Code.  Is there an equivalent set of settings to turn off in code to get around this issue?
