### ISSUE TITLE
Error encountered inside component with Shadow Dom

### ISSUE THREAD

**Issue by Emanuel1130** [Enngage/ngx-paypal#191]
Hello, 
I found a problem with ngx-paypal if trying to setup inside a component with shadow dom. 
This problem occures even if you only have a parent component with that encapsulation, such as your 'app.component.ts';

You can find here my fork project where I just added shadow dom as encapsulation.
https://stackblitz.com/edit/angular-ngx-paypal-9o64gg?file=src/app/app.component.ts

![image](https://user-images.githubusercontent.com/22767035/135410751-c5208fef-0c94-4f5c-87db-1fc95ea3aeca.png)

**Comment by Enngage** [comment]
I don't think this is ever gonna work because paypal adds it's stuff to 'real' DOM..
