### ISSUE TITLE
Remove Pay Later Button?

### ISSUE THREAD

**Issue by natekemp21** [Enngage/ngx-paypal#195]
According to paypal's [documentation](https://developer.paypal.com/docs/regional/th/checkout/reference/customize-sdk/#disable-funding), if you add the query parameter "disable-funding=credit" to the paypal script tag, it will remove the "Pay Later" button.  Is there any way to configure this in this library?

**Comment by Enngage** [comment]
Yeah, it should be. Add your custom query parameters to `advanced` configuration ([config.advanced.extraQueryParams](https://github.com/Enngage/ngx-paypal/blob/bb47ed606befa4abf66ea46086fe5d4e703fae25/projects/ngx-paypal-lib/src/lib/components/paypal.component.ts#L175))

**Comment by natekemp21** [comment]
Got it.  Thanks!
