### ISSUE TITLE
Dynamic (or) Updated amount not taken in Angular 5 PayPal

### ISSUE THREAD

**Issue by senthilmca90** [Enngage/ngx-paypal#2]
Ts Code:
---------
`public payPalConfig?: PayPalConfig;
 public finalAmount : number = 1;`

`ngOnInit(): void {
      this.initConfig();
    }`

  `private initConfig(): void {`
      `this.payPalConfig = new PayPalConfig(PayPalIntegrationType.ClientSideREST, PayPalEnvironment.Sandbox, {`
        `commit: true,`
        `client: {`
          `sandbox: 'mysandbox_key_XXXXXXXXXXXXXXXXXXXXXX'`
        `},`
        `button: {`
          `label: 'paypal',`
        `},`
        `onPaymentComplete: (data, actions) => {`
          `console.log('OnPaymentComplete');`
        `},`
        `onCancel: (data, actions) => {`
          `console.log('OnCancel');`
        `},`
        `onError: (err) => {`
          `console.log('OnError');`
        `},`
        `transactions: [{`
          `amount: {`
            `currency: 'USD',`
            `total: this.finalAmount`
          `}`
        `}]`
      `});`
    `}`
  `}`

Html Code:
------------

`<form>`
`<input type="number" name="finalAmount" [(ngModel)]="finalAmount" style="padding-bottom: 20px;">`
`<ngx-paypal [config]="payPalConfig" (click)="initConfig()"></ngx-paypal>`
`</form>`

how can I send a dynamic amount?

**Comment by Enngage** [comment]
The PayPal component is fully dynamic (meaning it will reinitialize each time you change the `config`) so I think you could go away with doing something like this when your price change:

```
this.payPalConfig = undefined;
this.payPalConfig = getYourConfigAgain();
```

Hope it helps!

**Comment by senthilmca90** [comment]
Hi @Enngage, Thank you for your response.
 I tried below code, but not updating the price value.

**Ts Code:**
------------

`export class MainComponent implements OnInit {`
    `public payPalConfig?: PayPalConfig;`
    `public finalAmount: number = 1;`
    `public allProduct : any = {};`
  `constructor() { }`
``
  `ngOnInit() {`
    `this.initConfig();`
  `}`
  `public selectedProduct(){`
      `this.finalAmount = 0;`
      `if(this.allProduct.laptop){`
        `this.finalAmount += 2;`
      `}`
      `if(this.allProduct.mobile){`
        `this.finalAmount += 3;`
      `}`
      `console.log("this.finalAmount ", this.finalAmount); // final amount result 5`
  `}`
``
  `public initConfig() {`
   ``
    `this.payPalConfig = new PayPalConfig(PayPalIntegrationType.ClientSideREST, PayPalEnvironment.Sandbox, {`
      `commit: true,`
      `client: {`
        `sandbox: 'mysandbox_key_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'`
      `},`
      `button: {`
        `label: 'paypal',`
      `},`
``
      `onPaymentComplete: (data, actions) => {`
        `console.log("onPaymentComplete")`
``
      `},   `
      `onCancel: (data, actions) => {`
        `console.log('OnCancel');`
      `},`
      `onError: (err) => {`
        `console.log('OnError');`
      `},`
      `transactions: [{`
        `amount: {`
            `total: this.finalAmount,  //not updated final amount result 5 `
          `currency: 'USD'`
          ``
        `}`
      `}]`
    `});`
  `}`
`}`

**Html Code** 
---------------

`<form>`
        `<input  type="checkbox" [(ngModel)]="allProduct.laptop" name="laptop" (change)="selectedProduct()" />laptop price - Rs : 2`
        `<input  type="checkbox" [(ngModel)]="allProduct.mobile" name="mobile" (change)="selectedProduct()" />laptop price - Rs : 3`
     `<br>`
    `Final Amount {{finalAmount}}`
`<ngx-paypal [config]="payPalConfig"></ngx-paypal>`
`</form>`

final amount 5. when I click PayPal checkout button I got a static value of amount 1.

**Comment by Enngage** [comment]
You are not reinitializing config as I mentioned in my last post. You need to call the `initConfig` when the price change - in your case when the selectedProduct() is called (init config inside this method).

**Comment by Enngage** [comment]
np. All working good now?

**Comment by senthilmca90** [comment]
Yes, working fine.

**Comment by Subir375** [comment]
nothing to do just bind the value property data by using this:
purchase_units:[
{ amount:{
currency_code:'INR'
....
value:this.amount
(amount comes from html file <input type="number" [(ngModel)]=amount #priceElem>)
