### ISSUE TITLE
ngx-paypal issues on MacOS

### ISSUE THREAD

**Issue by nikdow** [Enngage/ngx-paypal#201]
We have some reports of issues on MacOS, specifically the pop-up opens and then closes immediately.  We haven't been able to reproduce this but one report is from:
Mac OS Monterey Version 12.2.1
Chrome Version 98.0.4758.102 (Official Build) (arm64) 
Not seeing this on Windows or Android clients.
Angular version is 12.2

Will try to get more information to add here.

We are getting our code from:
https://www.npmjs.com/package/ngx-paypal
We are running npm v8.0.0.  I see v9.0.0 is available on npm, but I am having trouble relating npm version numbers to the git repository, nor can I figure out how to find release notes for major versions on npm.  

Any information would be appreciated, including whether there is a better place to ask these questions.

**Comment by Enngage** [comment]
This has probably something to do with the Paypal script, so maybe you can find out more info from the Paypal support. I can't really say whats going on as I'm not really developing the Paypal plugin itself, this library is relying on the official Paypal API.
