### ISSUE TITLE
How can I increase the timeout of requests to https://www.sandbox.paypal.com/xoplatform/logger/api/logger when initialising ngx-paypal component.

### ISSUE THREAD

**Issue by giri1991** [Enngage/ngx-paypal#21]
Hello, I am receiving this error on occasion : It is a timeout problem, it seems the request to the paypal api takes longer than the timeout limit.

error: "Error: No ack for postMessage xcomponent_init in h…://www.paypalobjects.com/api/checkout.js:2702:73)", timestamp: 1537433144648, windowID: "e1fb5a4657", pageID: "8ca0699f87", prev_corr_ids: ""

I have isolated the problem: it is when I add this addon called Intercom to the page where ngx-paypal is loaded. When I remove Intercom, this is not a problem. how could I increase the timeout limit to the request?

**Comment by Enngage** [comment]
Well, I don't have any timeouts in my code. What does the intercom do? How does it affect loading of paypal script since its working if you don't include it?

**Comment by tobywid** [comment]
Hi Richard - we aren't sure what Intercom is doing, but it seems to slow down the response from Paypal, so what we are looking for is a way to increase the Paypal timeout from 1000ms. Is there any way to set that option using ngx-paypal? 

Thanks

**Comment by Enngage** [comment]
Hi, there isn't. I don't use any timeouts anywhere in my code so it must be something else that is timing out... Maybe its the angular test timing out?
