### ISSUE TITLE
Support for Angular 15

### ISSUE THREAD

**Issue by zZeepo** [Enngage/ngx-paypal#221]
Good day 👋 

Thank you for maintaining this useful repository! :)
I would greatly appreciate support for the newly released version 15 of angular core.

Cheers
zZeepo

**Comment by MaxRuediger** [comment]
That would be really great!

**Comment by andreyjkee** [comment]
Any news about upgrade for angular v15 support?

**Comment by matiascamiletti** [comment]
Hi!

I created fork with Angular 15:

https://github.com/Tots-Agency/ngx-paypal

Install:

npm install --save @tots/ngx-paypal

**Comment by Enngage** [comment]
Just released update for v15.
