### ISSUE TITLE
Latest version 11.0.0 not available to compile

### ISSUE THREAD

**Issue by Crefelder** [Enngage/ngx-paypal#229]
paypal.component.d.ts is having an error with attribute count:

![image](https://user-images.githubusercontent.com/7198153/211841140-df64ce58-69e5-4043-a717-70d8371700c4.png)
![image](https://user-images.githubusercontent.com/7198153/211841417-a878d1e9-95db-4a54-8e92-d46e46b7f92b.png)

**Comment by Enngage** [comment]
Remove your build files and / or node_modules and do a clean install.
