### ISSUE TITLE
Compilation error when using ngx-paypal: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments

### ISSUE THREAD

**Issue by frantchessico** [Enngage/ngx-paypal#237]
The error "Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments" occurs when using the ngx-paypal package in an Angular application. This error indicates that the NgxPaypalComponent component, provided by the ngx-paypal package, is missing required type arguments to be properly declared.

On line 49 of the "paypal.component.d.ts" file inside the "node_modules/ngx-paypal/lib/components" directory, the error states that the component declaration is expected to have between 7 and 8 type arguments. However, only 6 type arguments are being provided, which results in the compilation error.

This error can prevent the Angular application from building successfully and can prevent the ngx-paypal component from being used correctly. To fix this error, you need to update the ngx-paypal package code or look for a newer version of the package that already fixes the error.

**Comment by Enngage** [comment]
I believe you just need to delete your node_modules and reinstall the package.
