### ISSUE TITLE
Can I only assign the "recipient_name" in the "transaction" informations?

### ISSUE THREAD

**Issue by ProgBiss** [Enngage/ngx-paypal#24]
Hello,

I've started using your work this week and now I encounter an issue/problem. 
When I initialize my "transaction" in the "payPalConfig", I want to initialize one field of the "shipping_address". I want to set the "recipient_name" to what's in my parameter and let the rest of the "shipping_address" empty.

So, the problem is that the PayPal pop-up close immediately and I got an error (400 Bad Request) if some field are empty or null. 
Is there a way to only set the "recipient_name"?

![image](https://user-images.githubusercontent.com/16880226/47588513-64f36680-d934-11e8-96ba-8449f57c9735.png)

Thank you,
NicBiss

**Comment by Gandalfulul** [comment]
`shipping_address: {
                recipient_name: 'Brian Robinson',
                line1: '',
                line2: '',
                city: '',
                country_code: '',
                postal_code: '',
                phone: '',
                state: ''
              },`

Didn't work ?

**Comment by ProgBiss** [comment]
> `shipping_address: { recipient_name: 'Brian Robinson', line1: '', line2: '', city: '', country_code: '', postal_code: '', phone: '', state: '' },`
> 
> Didn't work ?

I was using double quote so I thought after your response that it was maybe because of that, but I still got the same error...

**Comment by Enngage** [comment]
From your screenshot it seems that PayPal api is rejecting your request so I guess its not possible to do what you need with PayPal. When it comes to shipping_address, all I'm doing it simply providing an interface to help you write the code, but I'm essentially passing whatever you enter to shipping_address back to paypal.

**Comment by ProgBiss** [comment]
Oh... I will do with it then.

Thank you for your answer, that's appreciated.

**Comment by Enngage** [comment]
Sure, let me know if you found some other way or workaround. PayPal's documentation on this is pretty much non-existent so I don't even know what they expect exactly.
