### ISSUE TITLE
Issue with angular material tabs

### ISSUE THREAD

**Issue by DMZakaria** [Enngage/ngx-paypal#29]
Hi, 
I have an issue inside angular material tabs, on navigation the component disappear. I have recreated the issue here https://stackblitz.com/edit/angular-fwyntj

I don't see any logs on the browser console.
Please check.
Thank's

**Comment by digdig18** [comment]
Me too +1

**Comment by David782** [comment]
I had a similar issue yesterday. I inspected in the source code of the component and after a while, i suspected an early initialization of the button after the first time initialization in the initPayPal() function in ngx-paypal.js file.

Without loosing too much time, i tried a workaround using setTimeout() function and delaying the function call of a 1000ms, allowing some variables to be set.

Original function was:

`NgxPaypalComponent.prototype.initPayPal = /**
     * @return {?}
     */
    function () {
        // set unique paypal container button id
        this.payPalButtonContainerId = "" + this.payPalButtonContainerIdPrefix + this.getPseudoUniqueNumber();
        // check if paypal was already register and if so, don't add it to page again
        if (!window[this.paypalWindowName]) {
            // check if script is pending
            if (window[this.paypalWindowScriptInitiated] === true) {
                this.pollUntilScriptAvailable();
            }
            else {
                // register script and set global flag
                window[this.paypalWindowScriptInitiated] = true;
                this.addPayPalScriptToPage();
            }
        }
        else {
            // just register 
          _this.handleScriptRegistering();
		
        }
    };`

Edited function:

`NgxPaypalComponent.prototype.initPayPal = /**
     * @return {?}
     */
    function () {
        // set unique paypal container button id
        this.payPalButtonContainerId = "" + this.payPalButtonContainerIdPrefix + this.getPseudoUniqueNumber();
        // check if paypal was already register and if so, don't add it to page again
        if (!window[this.paypalWindowName]) {
            // check if script is pending
            if (window[this.paypalWindowScriptInitiated] === true) {
                this.pollUntilScriptAvailable();
            }
            else {
                // register script and set global flag
                window[this.paypalWindowScriptInitiated] = true;
                this.addPayPalScriptToPage();
            }
        }
        else {
            // just register payment
			**var _this = this;
			setTimeout(function() { // <-- SetTimeout() function, fix a bug delay container setting
				_this.handleScriptRegistering();
			}, 1000);**
        }
    };`

And it worked in my case.

I don't know if this could work in your case, but i think the cause is the same.

**Comment by Enngage** [comment]
If this is 'solved' by 'setTimeout' it might be that change detection is not running. Can you try running `detectChanges` when the tab is switched? See [https://angular.io/api/core/ChangeDetectorRef](https://angular.io/api/core/ChangeDetectorRef)

**Comment by MHKarl** [comment]
I was able to get my code working by calling initConfig on the ngInit and then recalling the function once I had my total price set to where I needed it to. Not sure if this helps anyone.
`let fn = _.after(this.productsOrder.length, x => {
      this.initConfig(); // after total is calculated call paypal init
  });
  this.initConfig();`
