### ISSUE TITLE
[question] switching to production recommendations and experience

### ISSUE THREAD

**Issue by dnmd** [Enngage/ngx-paypal#30]
First of, thanks for this nice lib! Kudo's! 

Second, how would one / is there a recommended way to switch from the sandbox to a production environment? During construction of the `PayPalConfig` object, both the `PayPalEnvironment.Sandbox` and  sandbox  `client` id are used. Using the `environment.ts` files are not that convenient since it is likely you want to test a production `--prod` build from the app with the sandbox credentials as well... Are there any suggestions?

Last, do you use this lib in production? Or are there any readers who do? It is nice to get some confirmation on the awesomeness of this lib!

**Comment by Enngage** [comment]
Hi and thank you!

To be honest I'm not exactly sure what you are asking. If you don't want to use sandbox environment, you are free to switch to production (see [paypal-environment](https://github.com/Enngage/ngx-paypal/blob/master/projects/ngx-paypal-lib/src/lib/models/paypal-environment.ts)).

This library, under the hood, eventually just calls global PayPal API that is registered via paypal script so there is really no reason for this not to work in production. [Here ](https://github.com/Enngage/ngx-paypal/blob/master/projects/ngx-paypal-lib/src/lib/components/paypal-component.ts#L213)you can see how I'm calling PayPal's API and you can compare it with [official documentation](https://developer.paypal.com/docs/checkout/integrate/#1-get-the-code).

**Comment by marcusmarch** [comment]
I'm planning on using this library soon in production mode, and will let you know how it goes. As to your original question, you can create a third environment file and give it a title/flag like --prod_paypal_sandbox. I had to do something very similar with another set of features in my angular project, let me know if you need more info.
