### ISSUE TITLE
TypeError: Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by ChaliasosKonstantinos** [Enngage/ngx-paypal#4]
When I try to initialize the PayPal Config it throws an error that **paypal** variable does not exist.
Thus it can't find the **render** property. 

The paypal variable is declared in the source code, but I doesn't seem to work for a strange reason.

**Angular** 6.0.0
**Angular CLI** 1.7.3
**Ngx-Paypal** 2.0.0

When I try to declare the paypal var in the node_modules folder then it recognizes it, but then it doesn't find Button property.

Any ideas why is that happening?

**Comment by ChaliasosKonstantinos** [comment]
@Enngage ,thanks for the quick reply. Here you go.

**Module**

```
...
import {NgxPayPalModule} from 'ngx-paypal';

@NgModule({
  declarations: [
   ....
  ],
  imports: [
    ...
    NgxPayPalModule
  ],
  schemas: [ ...],
  providers: [ ... ]
})

export class ProModule {
  constructor() {}
}
```

**HTML**
```
<a-random-div-inside-a-random-col-inside-a-random-row>
  <ngx-paypal [config]="payPalConfig"></ngx-paypal>
</a-random-div-inside-a-random-col-inside-a-random-row>
```

**TS**
```
...
import {PayPalConfig, PayPalEnvironment, PayPalIntegrationType} from 'ngx-paypal';

@Component({
  ....
})
export class TokensComponent implements OnInit {

  ...
  public payPalConfig?: PayPalConfig;

  constructor(some-random-services) { }

  ngOnInit() {
    ...
    this.initPayPalConfig();
  }

// ==================================================================
// Events
// ==================================================================
  ........

// ==================================================================
// Configurations
// ==================================================================
  .....

  private initPayPalConfig(): void {
    this.payPalConfig = new PayPalConfig(PayPalIntegrationType.ClientSideREST, PayPalEnvironment.Sandbox, {
      commit: true,
      client: {
        sandbox: 'My key'
      },
      button: {
        label: 'paypal',
      },
      onPaymentComplete: (data, actions) => {
        console.log('OnPaymentComplete');
        console.log(data);
      },
      onCancel: (data, actions) => {
        console.log('OnCancel');
        console.log(data);
      },
      onError: (err) => {
        console.log('OnError');
        console.log(err);
      },
      transactions: [{
        amount: {
          currency: 'EUR',
          total: 9
        }
      }]
    });
  }
}

```

**Console log error**

![console error](https://user-images.githubusercontent.com/5910443/40000997-e6594666-5795-11e8-9db7-55a93b0335fb.jpg)

**Line in paypal-component.js where error occurs**
![paypal-components](https://user-images.githubusercontent.com/5910443/40001031-f86b4e76-5795-11e8-82c0-36457b9b7339.jpg)

**Comment by Enngage** [comment]
@ChaliasosKonstantinos, thanks for the info. The error you see seems to indicate that the paypal script is not available. I've tried dynamically displaying/hiding the **ngx-paypal** component using `ngIf` and a button, but I wasn't able to reproduce it. 

I did rollout a new version with minor updates though I don't think they are related to your issue. If you could isolate it, perhaps in a sample Angular repo I would definitely take a further look.

**Comment by ChaliasosKonstantinos** [comment]
@Enngage , I updated the package but the problem still persists. 
The error is there because the script isn't loaded before rendering the button.
The only way to not have this error is either: 

1.  Load the button on html parts that are rendered immediately and not conditionally.
2.  Load the script programmatically on ngAfterViewInit on my own and handle the error of it try to load again by the ngx package.
3.  Load the script from my index.html, but that's wrong in so many ways 😄 

I tried to replicate the problem on StackBlitz, but there it works absolutely fine. Even inside of 2x conditionally displayed templates.

In the end I integrated paypal checkout without the package, but I would definitely choose the package on any situation that doesn't involve nesting of conditionally displayed templates.

I will try and replicate the issue in a new project tomorrow and link it to you. 

Thanks for your time 👍

**Comment by Enngage** [comment]
Sure :) I'll be sure to take a look once you are able to reproduce this one, thanks!

**Comment by Enngage** [comment]
I'm not sure if this is related or not, but new library package with ng-packgr should solve these issues. Can you try upgrading to latest version `3.0.0` ?

**Comment by ChaliasosKonstantinos** [comment]
@Enngage , installed the v3 and made the code to use ngx paypal instead of my implementation. It works fine. Not sure if it is the new release, or angular decided to work correctly today, because everything was correct before as well.

Either way, issues can be closed. Thanks!

**Comment by Enngage** [comment]
Yeah, it seems like the old packaging had some issues. Thanks for the info!
