### ISSUE TITLE
Get VALIDATION_ERROR with dynamic amount

### ISSUE THREAD

**Issue by GuysmoB** [Enngage/ngx-paypal#40]
Hi,

I get a VALIDATION_ERROR because the transaction amount is a dynamic variable. After logging the variable, it doesn't matches the error description. In case it's a hard coded value, the transaction works fine. I can't find useful informations from the request's JSON.  

Error details : 
`"name": "VALIDATION_ERROR",
    "details": [
        {
            "field": "transactions.amount",
            "issue": "Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by '.', optional thousands separator ',', limited to 7 digits before the decimal point and currency which is a valid ISO Currency Code"`

**component.html**
`<ngx-paypal [config]="payPalConfig"></ngx-paypal>
<input type="number" class="form-control" placeholder="Enter amount" [(ngModel)]="amount"/>`

**component.ts**
`
import { Component, OnInit, Input } from '@angular/core';
import { PayPalConfig, PayPalEnvironment, PayPalIntegrationType } from 'ngx-paypal';

@Component({
  selector: 'app-paypal',
  templateUrl: './paypal.component.html',
  styleUrls: ['./paypal.component.css']
})
export class PaypalComponent implements OnInit {

  amount: number;
  public payPalConfig?: PayPalConfig;

  ngOnInit(): void {
    this.initConfig();
  }

  private initConfig(): void {
    this.payPalConfig = new PayPalConfig(PayPalIntegrationType.ClientSideREST, PayPalEnvironment.Sandbox, {
      commit: true,
      client: {
        sandbox: '...',
      },
      button: {
        label: 'paypal',
        layout: 'vertical'
      },
      onAuthorize: (data, actions) => {
        console.log('Authorize');
        return undefined;
      },
      onPaymentComplete: (data, actions) => {
        console.log('OnPaymentComplete');
        console.log(data);
      },
      onCancel: (data, actions) => {
        console.log('OnCancel');
      },
      onError: err => {
          if (typeof this.amount === 'number') {
          console.log('NUMBER !!!!!!!!!!');
        } else if (typeof this.amount === 'string') {
          console.log('STRING !!!!!!!!!!');
        }
        console.log('Amount : ' + this.amount);
        console.log('OnError : ' + err);
      },
      onClick: () => {
        console.log('onClick');
      },
      validate: (actions) => {
        console.log(actions);
      },
      experience: {
        noShipping: true,
        brandName: '...'
      },
      transactions: [{
        amount: {
          currency: 'EUR',
          total: this.amount
        }
      }]
    });
  }
}
`

**Comment by Enngage** [comment]
Reinitialize `paypalConfig` each time your value changes - add value change event to your input field. The error you are getting is PayPal complaining that you are not passing in proper amount values (check request headers).
