### ISSUE TITLE
Transaction amount validation server side

### ISSUE THREAD

**Issue by heavenchains** [Enngage/ngx-paypal#41]
I need to validate the amount set to be paid from the client side with the server side for more security.

For example, on the client side a transaction for a certain product is created with the amount 100.
I want t call the server side with the transaction id and product details to validate the price set in the transaction.

**Comment by Enngage** [comment]
Then use `server side` integration and create your payment in `onAuthorize` callback.

Please note this is going to change with next version (currently available under `next` tag on npm) where you can do the same in `onApprove` method.
