### ISSUE TITLE
ERROR in : Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.

### ISSUE THREAD

**Issue by vipultaylor** [Enngage/ngx-paypal#42]
Getting this error as soon as I import the NgxPayPalModule module in any of my modules.

**Comment by Enngage** [comment]
Are you using barrel files? I'm importing `NgxPayPalModule` just fine in the demo application - feel free to download and try it as well - https://github.com/Enngage/ngx-paypal/blob/master/demo/app/app.module.ts

**Comment by vipultaylor** [comment]
I am using barrel files. Eventually I loaded an earlier version and made it
work.
