### ISSUE TITLE
Paypal buttons not showing in iOS ionic

### ISSUE THREAD

**Issue by rmabunga** [Enngage/ngx-paypal#50]
Hi, we want to be able to use paypal as a payment method for our app. We followed the installation instructions and it worked perfectly on the web but not on iOS.

When we inspected it, the body of the iframe is empty. Is there an extra step needed for using ngx-paypal in iOS applications?

Thanks.

**Comment by Enngage** [comment]
Hi, I'm not sure if the JavaScript SDK can be used within iOS. PayPal clearly separates iOS/Android/Javascript SDKs - see https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/client-side/ios/v4/ 

I didn't see PayPal mentioning the JavaScript SDK is supposed to work on mobiles, but feel free to correct me if I'm wrong.

**Comment by mgarciadash** [comment]
+1   Here !!!
Im trying to make it work on iOS, but iframe is empty.
Due Ionic works on Angular, the JavaScript SDK should work on it.   =/

**Comment by Enngage** [comment]
I don't believe there is anything I can do to support this. If anyone would have more details, feel free to share it here.
