### ISSUE TITLE
How to wait for a server response before to complete the payment

### ISSUE THREAD

**Issue by Ibbus93** [Enngage/ngx-paypal#53]
Hello, this is probably not an issue but instead an usability problem. There is a [correlated issue](https://github.com/Enngage/ngx-paypal/issues/6) but it's not exacly what I want to know.

**What I want to do**
When a client is concluding an order in my platform, I want to check the availabilty of the items that the customer wants to buy. If the order can be performed, then the customer can go on with the payment.

**Where I want to verify the availability**
In order to avoid some security issues regarding different solutions, using ngx-paypal 5.0.0 my idea was to check the availability in _onApprove_ and to continue with the payment only if the reservation went good

**What I have tried**
I have tried different paths:
- to transform onApprove on an async method and await for the reponse of the server, but the payment goes on eventually if some error is shown (in this case, onError is triggered)
- to transform onClick on an async method in the same way as above

**Notes**
I am sorry if this is not the right place, I have different ideas to perform this checks but they don't seem to me as secure as an approach using the callback functions of the paymet is. Thank you eventually for the help!

**Example code of my idea**

```
this.payPalConfig = {
  currency: 'EUR',
  clientId: clientId,
  createOrderOnClient: (data) => <ICreateOrderRequest>{
    intent: 'CAPTURE',
    purchase_units: [
      {
        amount: {
          currency_code: 'EUR',
          value: amount
        }
      }
    ]
  },
  onApprove: (data, actions) => {
    // At this point, before to complete the payment
    // I want to know if the reservation of the articles went good

    /* some serviceCall to be awaited */
  },
  onClientAuthorization: (data) => {
    console.log('onClientAuthorization', data);
    // Here the payment went good and a message of success is shown
  },
  onCancel: (data, actions) => {
    console.log('OnCancel', data, actions);
    // Here I perform the revert of reservation and a message of failure is shown
  },
  onError: err => {
    console.log('OnError', err);
    // Here I perform the revert of reservation and a message of failure is shown
  },
  onClick: () => {
    console.log('onClick');
  },
};
```

**Comment by Enngage** [comment]
Hey, in this case I think you should actually use the [server side integration](https://github.com/Enngage/ngx-paypal#creating-orders-on-server) where your back-end server does all the checking and if its valid, also creates the order and return its id.

I think the `onApprove` callback is a bit too late to perform the validation such as this. 

Is there any reason you couldn't use the server side integration?

**Comment by tommmn** [comment]
@Ibbus93 In your example you are using client side integration. as @Enngage said, you should shift your logic to the server. So when you creating the order you could check availability or your products before you actually create the order. You can't do it directly in the client since client integration only preforms the checkout. You could fetch your response from the server before you actually allowing the user to create the order, but its not safe and damage the integrity of your application.
