### ISSUE TITLE
How to block paypal popup until form validation is finished

### ISSUE THREAD

**Issue by tentyp00** [Enngage/ngx-paypal#54]
Hi,
I have form which must be validated on click paypal button how to handle it with angular 6/7 ?

**Comment by Enngage** [comment]
Hey, so you likely need to approach this the other way around - disable
(not i itialize) paypal until your form is valid. Its not possible to
cancel dialog after you click on the paypal buttons. If you need to perform
some more advanced validation before placing an order, you should use
server side intergration where your server is responsible for creating
order.

**Comment by tentyp00** [comment]
Thanks for your response. One more question about update of shipping address. I tried to call initConfig method always when shipping address in my system is changed but it looks like button is initialized only once with first set of data. It is possible to update somehow shipping parameter in purchase_units?

**Comment by Enngage** [comment]
I don't think its currently possible to reinitialize the PayPal buttons based on what I see in code. Maybe you could try destroying the component manually (calling ngOnDestroy) and then initializing again with. This may be something I could improve further on.

**Comment by tentyp00** [comment]
Maybe you could change private initializePayPal: boolean = true; to public and then I could call ngOnChanges with null parameter because now I cannot reinitialize script because of doPayPalCheck and   if (**this.initializePayPa**l && this.config && this.payPal && this.payPalButtonContainerElem)

**Comment by Enngage** [comment]
I'll try looking at possible options in near future.

**Comment by prindacerk** [comment]
@tentyp00 You can use Paypal Config's Validation option. It will prevent the paypal window from opening if it's not valid yet. I am using that as well.

**Comment by Enngage** [comment]
Related to https://github.com/Enngage/ngx-paypal/issues/58, closing this one
