### ISSUE TITLE
How to use sandbox?

### ISSUE THREAD

**Issue by creativeprogramming** [Enngage/ngx-paypal#56]
Can you please provide me an example of how configure ngx-paypal to use the paypal sandbox? Thanks

**Comment by creativeprogramming** [comment]
Is it

`      clientId: 'sb',`
?

**Comment by Enngage** [comment]
Yeah, thats right. I'm using it on the demo app, see https://github.com/Enngage/ngx-paypal/blob/master/demo/app/app.component.ts#L33

**Comment by creativeprogramming** [comment]
Thanks
