### ISSUE TITLE
Once paypal config is initialized, when initializing again on the same page, it doesn't update the paypal button 

### ISSUE THREAD

**Issue by khyechun** [Enngage/ngx-paypal#58]
Init config does not update button if used again on the same page.

In my case:
I change the value of the price, and call the initconfig method, but if it had already been initialized before it will not update the price. 
It does update though if i were to go to another route and back to the current route.

edit: I have also tried using this.paypalConfig = undefined, when price changes but it still shows the button there

**Comment by Enngage** [comment]
This is known and has been mentioned several times. I'm planning on improving this in near future.

**Comment by khyechun** [comment]
Ah alright. Thanks for informing me then and sorry for the trouble. Guess I'll need to think of a way to make this work

**Comment by khyechun** [comment]
Wow it works now. Thank you so much!

**Comment by Enngage** [comment]
Awesome, glad to hear it helps.
