### ISSUE TITLE
How to receive a server response from OnAuthorize method.

### ISSUE THREAD

**Issue by EzryVilla** [Enngage/ngx-paypal#6]
Hello, sorry if this is not the correct way to ask this.

I'm having trouble trying to receive a response from my server after the payment has been completed since the property "OnAuthorize" receives and Observable<null> and I was wondering if there was a way to change that into an actual value.

**Comment by Enngage** [comment]
Hi, the `OnAuthorize` is a function that gets executed when authorization is complete and it is an obsevable because you might want to do something asynchronous in it. I'm not quite sure what you are having troubles with, but if you don't need to use observable, just use `of`` rxjs parameter like this:

```
import { of } from 'rxjs';

 onAuthorize: (data, actions) => {
                   // do something
                   return of(undefined);
                },
```

**Comment by EzryVilla** [comment]
Thank you very much!

**Comment by dheerendrasingh5191445** [comment]
Hi engage first of all thanks but there is one question if i want to do server side integration then on payment method  how will i make it call my api and get the data.paymentID

**Comment by Enngage** [comment]
Hi, you need to use the `payment` callback which accepts `Obsevable` and this observable should be responsible for posting data to your server and your server is responsible for creating the payment and returning paymentId. You will likely need to use other SDK (i.e. .NET, Php) on server to create the payment if you go down this road.

**Comment by dheerendrasingh5191445** [comment]
Yeah i get when i use payment callback and call my api inside it then subcribe then it give error that observable<string> required in place of subscription

**Comment by Enngage** [comment]
I don't understand. You have to give it a Observable that returns paymentId from your server. I'm only converting observable to Promise which is what paypal expects and thats it. You can see that [here ](https://github.com/Enngage/ngx-paypal/blob/master/projects/ngx-paypal-lib/src/lib/components/paypal-component.ts#L161)

**Comment by dheerendrasingh5191445** [comment]
this.payPalConfig = new PayPalConfig(PayPalIntegrationType.ServerSideREST, PayPalEnvironment.Sandbox, {
      commit: true,
      button:{
        label:'paypal'
      },
      payment:(():Observable<string> =>{
        return this.http.post('http://localhost:5000/api/PayPalPayment/CreatePayment',{'url': 'localhost:4200'})
                        .subscribe( (data) => { "no"; });
      }),
    }
  }

this is what i am doing

**Comment by Enngage** [comment]
You are subscribing = you are not returning an Observable. You need to do something like:

`
this.payPalConfig = new PayPalConfig(PayPalIntegrationType.ServerSideREST, PayPalEnvironment.Sandbox, {
commit: true,
button:{
label:'paypal'
},
payment:(() => {
return this.http.post('http://localhost:5000/api/PayPalPayment/CreatePayment',{'url': 'localhost:4200'})
.pipe(map (data) => 'paymentId'));
}),
}
}
`

**Comment by dheerendrasingh5191445** [comment]
map does not find and its not working.
 return this.http.post('http://localhost:5000/api/PayPalPayment/CreatePayment',{'url': 'localhost:4200'})
                 .pipe((data) =>{ return data });

observable of response cannot assign in observable of string

**Comment by Enngage** [comment]
what is 'data'? Is it a string with paymentId? You really should look into rxjs if you are working with Angular as 'map' is pretty much the most used thing there is.

You can import it with: 

`import { map } from 'rxjs/operators';`
