### ISSUE TITLE
'updateOrderDetails' does not exist in type 'IAdvancedConfiguration

### ISSUE THREAD

**Issue by andreadompe** [Enngage/ngx-paypal#61]
Needs to update docs,
'updateOrderDetails' does not exist in type 'IAdvancedConfiguration

actually i see in the source
export interface IAdvancedConfiguration {
    commit?: TrueFalse;
    extraQueryParams?: IQueryParam[];
}

but the docs are

            advanced: {
                updateOrderDetails: {
                    commit: true
                }
            },

**Comment by iPazooki** [comment]
yeah, it should be: 
`
advanced: { commit: 'true' }
`

**Comment by Enngage** [comment]
Yeah, thanks for the info :)
