### ISSUE TITLE
transaction onCancel after payment

### ISSUE THREAD

**Issue by klide1010** [Enngage/ngx-paypal#62]
From yesterday my version of plugin make the correct steps to buy (open popup, insert Paypal account, etc...), but when it confirms payment go on "OnCancel" of createOrderOnClient method without any information and close popup.
Until yesterday evening I don't have any problem. 

Paypal says there's no problems and the transaction don't arrive to the server.
What kind of problem is?

Thanks in advance

P.S. I tried with 5.0.0 beta 8 and 10 without any changes

**Comment by Enngage** [comment]
The `onCancel` is called only triggered by PayPal (see https://github.com/Enngage/ngx-paypal/blob/master/projects/ngx-paypal-lib/src/lib/components/paypal.component.ts#L230) and so it seems that paypal is rejecting/cancelling your payment. I can't really tell why. Maybe you can take a look at `data` parameters of the onCancel event if there is any information or look at network tab in your browser.

**Comment by klide1010** [comment]
Paypal tell me  less minutes ago that the plugin don't call OnAuthorize method, so the transaction became null.
I make test with sandbox and live environment and in both case i have this problem.
Please can you help me to understand what's wrong? Thanks in advance

**Comment by Enngage** [comment]
You say it worked until yesterday evening, last release of this library was 15 days ago, how can I tell you what happened Yesterday? Maybe its your server not responding. You have to debug this on your end as per my suggestions in previous response. If you have a server performing the transaction, did you debug that?
