### ISSUE TITLE
Missed callbacks

### ISSUE THREAD

**Issue by hampton1122** [Enngage/ngx-paypal#63]
Currently in my config, I am doing an onApprove and once I get the actions.order.capture, I send the data to my api to put the transaction data into a SES queue. Every now and then the client does not get to the onApprove. We think the user must close the popup PayPal window after they submit. My question is, would it be better to use onClientAuthorization? I get the same data back. Which callback comes first...onApprove or onClientAuthorization? Thanks for your input.

**Comment by Enngage** [comment]
Hello, these callbacks are triggered by PayPal SDK and I merely 'forward' them to you. These functions are described at https://developer.paypal.com/docs/checkout/integrate/ which I would recommend you to read as it might give you better idea of what you should be using.
