### ISSUE TITLE
**Hello, Enngage.

### ISSUE THREAD

**Issue by Seeniea** [Enngage/ngx-paypal#64]
**Hello, Enngage.
In my case, following error occured.**

core.js:12501 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'config' since it isn't a known property of 'ngx-payapl'.
1. If 'ngx-payapl' is an Angular component and it has 'config' input, then verify that it is part of this module.

**Comment by aditisdm** [comment]
Hi Enngage,
I caught with the error.
core.js:12501 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'config' since it isn't a known property of 'ngx-payapl'.

**Comment by Enngage** [comment]
It's not 'ngx-payapl', but 'ngx-paypal'...

**Comment by aditisdm** [comment]
Sorry, typo mistake - ngx-paypal.
