### ISSUE TITLE
Issue in Chrome

### ISSUE THREAD

**Issue by creativeprogramming** [Enngage/ngx-paypal#65]
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.sandbox.paypal.com/xoplatform/logger/api/logger with MIME type text/html

**Comment by Enngage** [comment]
Please reproduce on stackblitz, I have no idea what it means and I don't see how relevant it could be to this library. The only thing I'm doing is including paypal's javascript SDK which works ok in standard scenarios.. I'm closing unless you can provide any reproducable instance.

**Comment by creativeprogramming** [comment]
and: [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

Button is not clickable
