### ISSUE TITLE
Component keeps triggering ngDoCheck lifecycle hook

### ISSUE THREAD

**Issue by Iar0** [Enngage/ngx-paypal#67]
I found out that the ngDoCheck lifecycle hook keeps being called, I reproduced the problem here: https://stackblitz.com/edit/angular-arxakx (open the console)

I saw that happening in version 4, still the same with the latest beta version (10 at the moment).

**Comment by Enngage** [comment]
This seems to have been caused by Angular if paypal is rendered in NgZone. I've rendered paypal outside of angular zone which seems to have fixed this issue.

**Comment by Iar0** [comment]
Just saw it, great! Remove the console.log and it would be perfect 🙌

**Comment by Enngage** [comment]
Yep, noticed it afterwards :-) Thanks :)
