### ISSUE TITLE
How to use production

### ISSUE THREAD

**Issue by tyndareosmasselos** [Enngage/ngx-paypal#68]
Hello! Thank you for the module you have created! I have one problem though. How can I integrate production id? Thank you.

**Comment by enzonotario** [comment]
Hi! just include it conditionally, like:
```
{
    ...
    clientId: environment.production ? environment.paypal.production : environment.paypal.sandbox,
    ...
}
```

**Comment by Iar0** [comment]
First you need to add the clientId in your environment files (environment.prod.ts, environment.ts, etc), in environment.prod.ts add your real one.
Then you need to import the `environment` file in your code and use the clientId. When you build for production, the values in environment.prod.ts will be picked up.

Check the angular docs for more info

**Comment by Enngage** [comment]
Yea, as guys above mention, use environment properties - https://angular.io/guide/build
