### ISSUE TITLE
on angular SSR its giving error n is not a constructor 

### ISSUE THREAD

**Issue by hmvmpire** [Enngage/ngx-paypal#69]
![DevTools - localhost:4000:home:checkout 2019-05-19 04-51-33](https://user-images.githubusercontent.com/47912240/57976466-1dc4e400-79f2-11e9-9c48-7705495e55cf.jpg)

**Comment by hmvmpire** [comment]
even on ng build --prod giving alot of warinings

**Comment by Enngage** [comment]
Hi, PayPal SDK is not supported on SSR as far as I can tell. It needs to be rendered by browser.
