### ISSUE TITLE
"custom" parameter on transactions

### ISSUE THREAD

**Issue by igorosabel** [Enngage/ngx-paypal#7]
Hi!

This is more of a request or a suggestion than an issue.

I have set up a `Webhook` that sends a message from Paypal to my server after the sale has been completed. But in the `IPayPalTransaction` interface, you have only declared the `amount` field. I want to send a `custom` parameter ([as the documentation says](https://developer.paypal.com/docs/api/payments/#payment_create)) with the id of my order to mark it as payed.

I have modified the `paypal-models.d.ts` in this way to allow it:

```
export interface IPayPalTransaction {
    amount: IPayPalAmount;
    custom: string;
}
```

Thanks, this library works flawlessly from the very beginning following your demo.

**Comment by Enngage** [comment]
Hey, glad to hear that! I'll add extra parameter to the `IPayPalTransaction` interface as you suggest in a form of generic property. I hope to release it this week.

Thanks for the idea!

**Comment by Enngage** [comment]
I've added `custom` parameter to `3.0.0` release
