### ISSUE TITLE
Payout

### ISSUE THREAD

**Issue by kartikdjax** [Enngage/ngx-paypal#70]
I have sandbox account with APP and clientId, i need to show paypal button then need to pay my customer from my account which owns clientid. Can you guide me on this.

**Comment by Enngage** [comment]
I have no idea what this means, sorry man.

**Comment by kartikdjax** [comment]
Hi Richard Sustek,
Means i need to do payout process from my paypal sandbox account to other paypal users using registered paypal email id. I can collect my user paypal email id, then i need to pay amount from my account using paypal button. as like here https://developer.paypal.com/docs/payouts/#payouts-flow

**Comment by Enngage** [comment]
This library is based on JavasScript SDK used for checkout as described here - https://developer.paypal.com/docs/checkout/ 

Payouts are not related to this I'm afraid.

**Comment by kartikdjax** [comment]
Okay, can you suggest me any ideas, since i can do this using PHP or 
Java as server side. But here i need to do this using Angular client 
side application. So only asked. If you have any idea kindly provide 
some details.

**Comment by Enngage** [comment]
You have to use PayPal's API directly - https://developer.paypal.com/docs/api/payments.payouts-batch/v1/ 

You can do that from within any language, though I'm not sure how secure would that be for Angular apps unless you used Server side rendering. Anyway, I've never used payouts and can't tell you any more than that.
