### ISSUE TITLE
IPayPalButtonStyle is missing "credit" and "buynow"

### ISSUE THREAD

**Issue by elementalPRESS** [Enngage/ngx-paypal#72]
Please can you add these two options?

Furthermore, please can you give support for the "Funding methods"? That is because PayPal doesn't show the "Credit Card" in Germany by default (and written in the docs), but something really irrelevant which cannot be modified.

Thx and best wishes,
Lars

**Comment by Enngage** [comment]
I may look into that. Feel free to pass your own object with your configuration in the meantime. Use `any` to bypass compiler and it will work just fine :-)

**Comment by AbuHani** [comment]
@elementalPRESS if you disabled the Credit Card button let me know please.
i have same issue.

i tried passing the object as mentioned [here](https://developer.paypal.com/docs/archive/checkout/how-to/customize-button/#multiple-button-layout)

`
// Customize button (optional)
style: {
 layout: 'horizontal',
 fundingicons: 'true',
},

funding: {
 allowed: [ paypal.FUNDING.CARD ],
 disallowed: [ paypal.FUNDING.CREDIT ]
}
`
didn't work with me

**Comment by awinnen** [comment]
@AbuHani 
use
`advanced: {
        extraQueryParams: [
          { name: 'disable-funding', value: 'credit' }
        ]
      },`

**Comment by Enngage** [comment]
Closing as this is solved with query params
