### ISSUE TITLE
Get error message

### ISSUE THREAD

**Issue by GuysmoB** [Enngage/ngx-paypal#75]
Hi,

I would like to inform the user if an error occurs with the Paypal error message but I can't get the error code, message or whatever. Each time I got 'undefined' when I try to access to this properties.

Here an example : 
`OnError Error: Order Api response error:
{
    "name": "UNPROCESSABLE_ENTITY",
    "details": [
        {
            "field": "/purchase_units/0/amount/value",
            "value": "10000000",
            "issue": "MAX_VALUE_EXCEEDED",
            "description": "Should be less than or equal to 9999999.99."
        }
    ],
    "message": "The requested action could not be performed, semantically incorrect, or failed business validation.",
    "debug_id": "8536748831a6",
    "links": [
        {
            "href": "https://developer.paypal.com/docs/api/orders/v2/#error-MAX_VALUE_EXCEEDED",
            "rel": "information_link",
            "method": "GET"
        }
    ]
}`

Thank you for any help !

**Comment by Enngage** [comment]
How are you accessing the error property?

**Comment by GuysmoB** [comment]
Inside the Paypal config : 
`onCancel: (data, actions) => {
        console.log('OnCancel', data, actions);
      },
      onError: err => {
        console.log('OnError', err);
        console.log('name', err.name);
        console.log('message', err.name.message);
        console.log('value', err.name.value);
        console.log('code', err.name.code);
        console.log('description', err.name.description);
        console.log('msg', err.name.msg);
      },`
Thanks

**Comment by GuysmoB** [comment]
Any idea to get the error description message ?
`onError: err => { 
    console.log('OnError', err);
}`
Thank you !
