### ISSUE TITLE
Cannot read property 'eligible' of undefined

### ISSUE THREAD

**Issue by AbuHani** [Enngage/ngx-paypal#76]
Hi, i used this package in my project and it was working nice

i tried it today and i got some error in my console
 
`ERROR TypeError: Cannot read property 'eligible' of undefined
`

i don't know from where this issue, also i didn't change any things in my code

<img width="1422" alt="Screen Shot 2019-05-30 at 12 54 02 AM" src="https://user-images.githubusercontent.com/17643875/58594803-6349a280-8277-11e9-86bf-4cec096f0911.png">

**Comment by richardmvb** [comment]
It's happens with me too, and I've using the ngx-paypal for a while.

And I get the same error on your example page: https://enngage.github.io/ngx-paypal/

**Comment by Enngage** [comment]
I'm not having this issue on the demo.. Are you still having the issue? Since the PayPal script is loaded automatically and they do apply patches, it might be they broke something and fixed it already.
