### ISSUE TITLE
Can't send feedback to application from the Init functions

### ISSUE THREAD

**Issue by tommmn** [Enngage/ngx-paypal#77]
I used to have an option to send feedback from inside the function. For example, I had a "Processing screen with a spinner between server authorization & capture and when I get result, I initiate new success screen.
I didn't check it for a while but I did now and I think since the :

> commit - a4b8e1b1390a08d1f81feee4a058c91829c0bdfb

When the this.ngZone.runOutsideAngular introduced it messed up with this feature.
I'm not longer able to send feedback from those functions.
I also tried to manually call detect on the cdr but it throws errors plus doesn't work.

**Comment by Enngage** [comment]
There is a problem when PayPal is used within Angular in that Angular automatically and infinitely calls `ngDoCheck` callback which is causing performance issues and is simply wrong. 

I have not been able to find a way to resolve this other than using PayPal outside the Angular zone. You might still be able to share data through global property or some other way that does not rely on Angular specific code (includes e.g. DI as far as I call)

**Comment by tommmn** [comment]
@Enngage Hey, so I just figured it out.
My mistake was that I tried to call the cdr to force detection, but since the code executing outside of Angular context it didn't do anything. After some reading about the ngZone behavior, this is my solution.

**For future visitors:**
If you would like to get notifications from inside the paypal function, you have to call:
```
this.ngZone.run(() => {
    /** 
        Do something here...
    */
});
```
So when you trigger ngZone.run(), Angular understands that you would like to run this action inside Angular context and would execute it in the right context.
It's worth to mentioned it in the docs maybe since it pretty common scenario to update the user what action is processing right now and what is the progress. (especially when it comes to server side integrations)

**Comment by Enngage** [comment]
Can you try with latest `5.0.0` release and without you running the ngZone? I've added ngZone to all callbacks and it should likely help.

**Comment by tommmn** [comment]
@Enngage So I've tried to upgrade the package and exclude my own ngZone calls, but it doesn't work.
Only if I brought back my own ngZone calls it works.
Maybe it has something to do with the context of the code. 
--
Also, I've received sometimes an error:
`ERROR Error: Window closed for postrobot_method before response`
Which is probably cause of *ngIf, but when I call with my own ngZone it reduce the times of this error appears to almost none. Maybe it worth investigate.

**Comment by GuysmoB** [comment]
Hi,
I think I have a similar problem. The Paypal button is display on a modal and I want to inform the user about the paiement state, relate to OnCancel(), onClientAuthorization(), OnError().
In these functions, I just want to print something on my template but It take many seconds to display it. Like Angular is waiting the Paypal process before execute code related to DOM.

**Comment by Enngage** [comment]
Just to be sure - are you guys calling 'detectChanges' once you change some
local properties? Its part of the ChangeDetectorRef and is used for the
purpose of manually detecting changes in angular app which is what this
seems to be about.

**Comment by tommmn** [comment]
@Enngage As I said before, I did call the cdr to manually detect changes, but I didn't try again after your update. After your update I've tried to remove my own ngZone calls and relay on yours but it didn't work.
I will try to call detectChanges again after your update. But, if I also should call the cdr, maybe its better to remove your new ngZone calls and just explicitly add ngZone.run() when ever you need. We should check what is the best practices to use each. I will update after tests with cdr.

**Comment by tommmn** [comment]
@Enngage Ok so if I remove my calls to ngZone and use cdr.detectChanges() its working (version 5.0.0).
Now the questions are:

1. Whats the better solution: Force the call to ngZone in the base code and add cdr.detectChanges() in the app code each time you update some local variables, or run the library code outside the zone (like before the last commit) and manually call ngZone to update specifically (does not need to run detectChanges()).
2. Maybe we can extend the library code and add new event that expose the current status of the process, since this is not possible right now.

I think that the second solution is much more cleaner and provides more control over the inner process.
So for example:

- INIT_CONFIG - Start the initial paypal config
- CREATE_ORDER - In create order stage
- EXECUTE_ORDER_START - ....
- EXECUTE_ORDER_DONE - ....

and so on..
So with this solution, we dont event need to care about manually call extra detect changes or affect the zone, we only need to subscribe to the event emitter and get the ability to do with that information something.
Its only some ideas of features we can implement for future versions.

**Comment by riedflor** [comment]
> Can you try with latest `5.0.0` release and without you running the ngZone? I've added ngZone to all callbacks and it should likely help.

For me adding ngZone to all callbacks in `5.0.0` works properly, one was missing for onClientAuthorization, see #99
