### ISSUE TITLE
Issue loading JS SDK

### ISSUE THREAD

**Issue by mmedic** [Enngage/ngx-paypal#78]
In the last couple of weeks, I started getting a 400 error when the library tries to load the SDK. In Chrome dev tools, I see 400 error on URL: GET https://www.paypal.com/sdk/js?client-id=MY_CLIENT_ID&currency=USD&commit=true. Has something in the library of=r SDK changed to cause this? I verified that my client id is correct.

Same is happening on the demo site: https://enngage.github.io/ngx-paypal/

**Comment by Enngage** [comment]
I'm not having any issues with the live demo.. What exact error are you receiving? If you are getting 4.x.y from just loading the script from paypal then I'm afraid there is nothing I can do about that - its paypal who is rejecting your request.  It could be related to your country/network or maybe something completely else. If you get some particular error code, you might reach out to PayPal support to let you know why you cannot load the script.

**Comment by mmedic** [comment]
Seems to be something with the browser cache or cookies. It is working now.
