### ISSUE TITLE
How can I add a custom field?

### ISSUE THREAD

**Issue by HansDaigle** [Enngage/ngx-paypal#82]
In the [paypal documentation](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNIntro/?mark=IPN#ipn-protocol-and-architecture) they say:

"
For example, if you are using PayPal buttons, in the button form code, you just need to add an extra hidden input form variable to set a value for the custom variable.

`<input type="hidden" name="custom" value="[UserID],[PartNumber]"/>`
"

How could I add that `<input>` to the `<ngx-paypal [config]="payPalConfig"></ngx-paypal>`?

I'm using the `ICreateOrderRequest` to make my call.

This is especially useful when working with IPN to keep track of which user made the payment.

**Comment by jeffj6123** [comment]
Hey, I am also interested in the proper way of handling this.

**Comment by Enngage** [comment]
Can't you just add those input in your own DOM? why would ngx-paypal component be adding these inputs for you?
