### ISSUE TITLE
Looking for full example?

### ISSUE THREAD

**Issue by elementalPRESS** [Enngage/ngx-paypal#83]
Please can you provide a full working code example, with taxes, shippings etc. I'm trying since a while to get it to work with the new version but it wont.

Thx and regards,
Lars

**Comment by Enngage** [comment]
Create order is mirroring PayPal API so you can use whatever is defined at https://developer.paypal.com/docs/api/orders/v2/#orders_create 

In fact, I'm only providing interfaces and just forwarding object that you pass to create order methods. For whole checkout overview, you can refer to https://developer.paypal.com/docs/checkout/integrate/#
