### ISSUE TITLE
New release to include a paypal sdk fix?

### ISSUE THREAD

**Issue by bahrmichael** [Enngage/ngx-paypal#85]
There were issues reported to paypal in https://github.com/paypal/paypal-checkout-components/issues/404 and https://github.com/paypal/paypal-checkout-components/issues/1029. According to 1029 the release containing the fix was on Feb, 23rd while the last release of ngx-paypal was Feb, 19th (https://github.com/Enngage/ngx-paypal/releases/tag/5.0.0-beta.12). Would you mind doing another release that contains the latest SDK version?

**Comment by Enngage** [comment]
Hey,

I'm not actually shipping PayPal's code along with this library as that is against the best practices. The idea is that you load PayPal's SDK using with `https://www.paypal.com/sdk/js` which should contain all latest patches. 

You can see how I'm loading the SDK at -> https://github.com/Enngage/ngx-paypal/blob/master/projects/ngx-paypal-lib/src/lib/services/paypal-script.service.ts#L51

So, in essense, you should already have the latest PayPal version.

**Comment by bahrmichael** [comment]
Thanks for the quick response! I'll look into why the bug still appears on my side.
