### ISSUE TITLE
client-id not recognized for either production or sandbox:

### ISSUE THREAD

**Issue by suyashscisin** [Enngage/ngx-paypal#87]
Hello,
I am facing one issue, ClientId for sandbox is working but when I change it to production ClientId It starts giving below error:-
client-id not recognized for either production or sandbox:

Please suggest is my clientId is wrong for production or do I need to make more changes in code to work for production environment

**Comment by Enngage** [comment]
This is a matter of your paypal account, I'm not throwing such exceptions at all. Please verify your PayPal acccount is valid and active.

**Comment by RENSAAS** [comment]
cloud-01ACD8-0C355D-0037D
A.pdf"... -->
-

APRIL 
PT
