### ISSUE TITLE
Issue in checkout.js

### ISSUE THREAD

**Issue by Jofiman** [Enngage/ngx-paypal#88]
Something is happening in checkout.js.

Some version conflict on init();

I can t Init my payapl component because of this.

Im sending image to see errors.

Best regards,

Jovan

![image](https://user-images.githubusercontent.com/11769172/66524486-e23acb80-eaf2-11e9-8974-cc562943f482.png)

![image (1)](https://user-images.githubusercontent.com/11769172/66524502-ec5cca00-eaf2-11e9-95ad-2b6463d60173.png)

**Comment by Enngage** [comment]
Hey,

There is an incorrect syntax in your code - which is why you get the exception with "<<" signs. Did you remove these in your initLogger method?

**Comment by Jofiman** [comment]
Hey @Enngage problem was in them. They fixed last night. It was some remaining code that was not merge. 

Thx for the reply.

Best regards,

Jovan
