### ISSUE TITLE
ionic App is crashing when i click on paypal payment button .

### ISSUE THREAD

**Issue by ammyGaba** [Enngage/ngx-paypal#89]
i am using paypal payment gateway in my ionic hybrid app . but when i  click on paypal button app carshes .. but on web its working fine .

**Comment by Enngage** [comment]
You need to use Ionic libs such as - https://ionicframework.com/docs/native/paypal 

This library is using PayPal's JavaScript API.

**Comment by fmendoza** [comment]
I believe something changed on the Paypal SDK JS. Some months ago ngx-paypal was working in a cordova environment (iOS / Android) now like @ammyGaba said the app crashed right after you press the paypal button.

Logs:

```
SystemWebChromeClient: http://localhost/pages-thanks-page-thanks-page-module-es2015.js: Line 1000 : OnError Error: Window navigated away
SystemWebChromeClient: https://www.sandbox.paypal.com/smart/buttons?style.label=paypal&style.layout=vertical&style.color=gold&style.shape=rect&style.tagline=false&onShippingChange=true&components.0=buttons&locale.country=MX&locale.lang=es&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVRmYmN1UVJ5M09qa2hpa1I0UFRCQ1NjNkZFeUw2YXQxOUE5ZVNiMldTRlRfVmhJYW14Tm5fV21INWVHcUY0cVJKdTZIWkk2VXhwLWpDY3cmY3VycmVuY3k9RVVSIiwic3RhZ2VIb3N0IjpudWxsLCJhcGlTdGFnZUhvc3QiOm51bGx9&clientID=ATfbcuQRy3OjkhikR4PTBCSc6FEyL6at19A9eSb2WSFT_VhIamxNn_WmH5eGqF4qRJu6HZI6Uxp-jCcw&sessionID=8701faad75_mtc6mjq6mjg&buttonSessionID=610c5a1cf6_mtc6mjg6ndq&env=sandbox&fundingEligibility=eyJwYXlwYWwiOnsiZWxpZ2libGUiOnRydWV9LCJ2ZW5tbyI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJpdGF1Ijp7ImVsaWdpYmxlIjpmYWxzZX0sImNyZWRpdCI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJzZXBhIjp7ImVsaWdpYmxlIjpmYWxzZX0sImlkZWFsIjp7ImVsaWdpYmxlIjpmYWxzZX0sImJhbmNvbnRhY3QiOnsiZWxpZ2libGUiOmZhbHNlfSwiZ2lyb3BheSI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJlcHMiOnsiZWxpZ2libGUiOmZhbHNlfSwic29mb3J0Ijp7ImVsaWdpYmxlIjpmYWxzZX0sIm15YmFuayI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJwMjQiOnsiZWxpZ2libGUiOmZhbHNlfSwiemltcGxlciI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJ3ZWNoYXRwYXkiOnsiZWxpZ2libGUiOmZhbHNlfSwicGF5dSI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJ0cnVzdGx5Ijp7ImVsaWdpYmxlIjpmYWxzZX0sImJsaWsiOnsiZWxpZ2libGUiOmZhbHNlfSwib3h4byI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJtYXhpbWEiOnsiZWxpZ2libGUiOmZhbHNlfSwiYm9sZXRvIjp7ImVsaWdpYmxlIjpmYWxzZX0sImNhcmQiOnsiZWxpZ2libGUiOnRydWUsImJyYW5kZWQiOnRydWUsInZlbmRvcnMiOnsidmlzYSI6eyJlbGlnaWJsZSI6dHJ1ZX0sIm1hc3RlcmNhcmQiOnsiZWxpZ2libGUiOnRydWV9LCJhbWV4Ijp7ImVsaWdpYmxlIjp0cnVlfSwiZGlzY292ZXIiOnsiZWxpZ2libGUiOmZhbHNlfSwiaGlwZXIiOnsiZWxpZ2libGUiOmZhbHNlfSwiZWxvIjp7ImVsaWdpYmxlIjpmYWxzZX0sImpjYiI6eyJlbGlnaWJsZSI6ZmFsc2V9fX19&platform=mobile&currency=EUR&intent=capture&commit=true: Line 977 : Scripts may close only the windows that were opened by it.
chromium: [INFO:CONSOLE(977)] "Scripts may close only the windows that were opened by it.", source: https://www.sandbox.paypal.com/smart/buttons?style.label=paypal&style.layout=vertical&style.color=gold&style.shape=rect&style.tagline=false&onShippingChange=true&components.0=buttons&locale.country=MX&locale.lang=es&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVRmYmN1UVJ5M09qa2hpa1I0UFRCQ1NjNkZFeUw2YXQxOUE5ZVNiMldTRlRfVmhJYW14Tm5fV21INWVHcUY0cVJKdTZIWkk2VXhwLWpDY3cmY3VycmVuY3k9RVVSIiwic3RhZ2VIb3N0IjpudWxsLCJhcGlTdGFnZUhvc3QiOm51bGx9&clientID=ATfbcuQRy3OjkhikR4PTBCSc6FEyL6at19A9eSb2WSFT_VhIamxNn_WmH5eGqF4qRJu6HZI6Uxp-jCcw&sessionID=8701faad75_mtc6mjq6mjg&buttonSessionID=610c5a1cf6_mtc6mjg6ndq&env=sandbox&fundingEligibility=eyJwYXlwYWwiOnsiZWxpZ2libGUiOnRydWV9LCJ2ZW5tbyI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJpdGF1Ijp7ImVsaWdpYmxlIjpmYWxzZX0sImNyZWRpdCI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJzZXBhIjp7ImVsaWdpYmxlIjpmYWxzZX0sImlkZWFsIjp7ImVsaWdpYmxlIjpmYWxzZX0sImJhbmNvbnRhY3QiOnsiZWxpZ2libGUiOmZhbHNlfSwiZ2lyb3BheSI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJlcHMiOnsiZWxpZ2libGUiOmZhbHNlfSwic29mb3J0Ijp7ImVsaWdpYmxlIjpmYWxzZX0sIm15YmFuayI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJwMjQiOnsiZWxpZ2libGUiOmZhbHNlfSwiemltcGxlciI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJ3ZWNoYXRwYXkiOnsiZWxpZ2libGUiOmZhbHNlfSwicGF5dSI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJ0cnVzdGx5Ijp7ImVsaWdpYmxlIjpmYWxzZX0sImJsaWsiOnsiZWxpZ2libGUiOmZhbHNlfSwib3h4byI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJtYXhpbWEiOnsiZWxpZ2libGUiOmZhbHNlfSwiYm9sZXRvIjp7ImVsaWdpYmxlIjpmYWxzZX0sImNhcmQiOnsiZWxpZ2libGUiOnRydWUsImJyYW5kZWQiOnRydWUsInZlbmRvcnMiOnsidmlzYSI6eyJlbGlnaWJsZSI6dHJ1ZX0sIm1hc3RlcmNhcmQiOnsiZWxpZ2libGUiOnRydWV9LCJhbWV4Ijp7ImVsaWdpYmxlIjp0cnVlfSwiZGlzY292ZXIiOnsiZWxpZ2libGUiOmZhbHNlfSwiaGlwZXIiOnsiZWxpZ2libGUiOmZhbHNlfSwiZWxvIjp7ImVsaWdpYmxlIjpmYWxzZX0sImpjYiI6eyJlbGlnaWJsZSI6ZmFsc2V9fX19&platform=mobile&currency=EUR&intent=capture&commit=true (977)
CordovaWebViewImpl: onPageDidNavigate(about:blank)
CordovaWebViewImpl: onPageFinished(about:blank)
ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
CordovaActivity: Paused the activity.
CordovaActivity: Stopped the activity.
CordovaActivity: CordovaActivity.onDestroy()
CordovaWebViewImpl: >>> loadUrl(about:blank)
AwContents: WebView.destroy() called while WebView is still attached to window.token=
cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.a(PG:132)
        at tD0.loadingStateChanged(PG:2)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:386)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2019-10-30 11:28:50.929 22924-23008/it.extensione.bella D/ZrHung.AppEyeUiProbe: Current Activity:false
2019-10-30 11:28:50.929 22924-23008/it.extensione.bella D/ZrHung.AppEyeUiProbe: not watching, wait.

```

**Comment by vasconcelosvcd** [comment]
> You need to use Ionic libs such as - [ionicframework.com/docs/native/paypal](https://ionicframework.com/docs/native/paypal)
> 
> This library is using PayPal's JavaScript API.

This api is deprecated and Paypal does not offer support anymore...


> I believe something changed on the Paypal SDK JS. Some months ago ngx-paypal was working in a cordova environment (iOS / Android) now like @ammyGaba said the app crashed right after you press the paypal button.
> 
> Logs:
> 
> ```
> SystemWebChromeClient: http://localhost/pages-thanks-page-thanks-page-module-es2015.js: Line 1000 : OnError Error: Window navigated away
> SystemWebChromeClient: https://www.sandbox.paypal.com/smart/buttons?style.label=paypal&style.layout=vertical&style.color=gold&style.shape=rect&style.tagline=false&onShippingChange=true&components.0=buttons&locale.country=MX&locale.lang=es&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVRmYmN1UVJ5M09qa2hpa1I0UFRCQ1NjNkZFeUw2YXQxOUE5ZVNiMldTRlRfVmhJYW14Tm5fV21INWVHcUY0cVJKdTZIWkk2VXhwLWpDY3cmY3VycmVuY3k9RVVSIiwic3RhZ2VIb3N0IjpudWxsLCJhcGlTdGFnZUhvc3QiOm51bGx9&clientID=ATfbcuQRy3OjkhikR4PTBCSc6FEyL6at19A9eSb2WSFT_VhIamxNn_WmH5eGqF4qRJu6HZI6Uxp-jCcw&sessionID=8701faad75_mtc6mjq6mjg&buttonSessionID=610c5a1cf6_mtc6mjg6ndq&env=sandbox&fundingEligibility=eyJwYXlwYWwiOnsiZWxpZ2libGUiOnRydWV9LCJ2ZW5tbyI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJpdGF1Ijp7ImVsaWdpYmxlIjpmYWxzZX0sImNyZWRpdCI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJzZXBhIjp7ImVsaWdpYmxlIjpmYWxzZX0sImlkZWFsIjp7ImVsaWdpYmxlIjpmYWxzZX0sImJhbmNvbnRhY3QiOnsiZWxpZ2libGUiOmZhbHNlfSwiZ2lyb3BheSI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJlcHMiOnsiZWxpZ2libGUiOmZhbHNlfSwic29mb3J0Ijp7ImVsaWdpYmxlIjpmYWxzZX0sIm15YmFuayI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJwMjQiOnsiZWxpZ2libGUiOmZhbHNlfSwiemltcGxlciI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJ3ZWNoYXRwYXkiOnsiZWxpZ2libGUiOmZhbHNlfSwicGF5dSI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJ0cnVzdGx5Ijp7ImVsaWdpYmxlIjpmYWxzZX0sImJsaWsiOnsiZWxpZ2libGUiOmZhbHNlfSwib3h4byI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJtYXhpbWEiOnsiZWxpZ2libGUiOmZhbHNlfSwiYm9sZXRvIjp7ImVsaWdpYmxlIjpmYWxzZX0sImNhcmQiOnsiZWxpZ2libGUiOnRydWUsImJyYW5kZWQiOnRydWUsInZlbmRvcnMiOnsidmlzYSI6eyJlbGlnaWJsZSI6dHJ1ZX0sIm1hc3RlcmNhcmQiOnsiZWxpZ2libGUiOnRydWV9LCJhbWV4Ijp7ImVsaWdpYmxlIjp0cnVlfSwiZGlzY292ZXIiOnsiZWxpZ2libGUiOmZhbHNlfSwiaGlwZXIiOnsiZWxpZ2libGUiOmZhbHNlfSwiZWxvIjp7ImVsaWdpYmxlIjpmYWxzZX0sImpjYiI6eyJlbGlnaWJsZSI6ZmFsc2V9fX19&platform=mobile&currency=EUR&intent=capture&commit=true: Line 977 : Scripts may close only the windows that were opened by it.
> chromium: [INFO:CONSOLE(977)] "Scripts may close only the windows that were opened by it.", source: https://www.sandbox.paypal.com/smart/buttons?style.label=paypal&style.layout=vertical&style.color=gold&style.shape=rect&style.tagline=false&onShippingChange=true&components.0=buttons&locale.country=MX&locale.lang=es&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVRmYmN1UVJ5M09qa2hpa1I0UFRCQ1NjNkZFeUw2YXQxOUE5ZVNiMldTRlRfVmhJYW14Tm5fV21INWVHcUY0cVJKdTZIWkk2VXhwLWpDY3cmY3VycmVuY3k9RVVSIiwic3RhZ2VIb3N0IjpudWxsLCJhcGlTdGFnZUhvc3QiOm51bGx9&clientID=ATfbcuQRy3OjkhikR4PTBCSc6FEyL6at19A9eSb2WSFT_VhIamxNn_WmH5eGqF4qRJu6HZI6Uxp-jCcw&sessionID=8701faad75_mtc6mjq6mjg&buttonSessionID=610c5a1cf6_mtc6mjg6ndq&env=sandbox&fundingEligibility=eyJwYXlwYWwiOnsiZWxpZ2libGUiOnRydWV9LCJ2ZW5tbyI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJpdGF1Ijp7ImVsaWdpYmxlIjpmYWxzZX0sImNyZWRpdCI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJzZXBhIjp7ImVsaWdpYmxlIjpmYWxzZX0sImlkZWFsIjp7ImVsaWdpYmxlIjpmYWxzZX0sImJhbmNvbnRhY3QiOnsiZWxpZ2libGUiOmZhbHNlfSwiZ2lyb3BheSI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJlcHMiOnsiZWxpZ2libGUiOmZhbHNlfSwic29mb3J0Ijp7ImVsaWdpYmxlIjpmYWxzZX0sIm15YmFuayI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJwMjQiOnsiZWxpZ2libGUiOmZhbHNlfSwiemltcGxlciI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJ3ZWNoYXRwYXkiOnsiZWxpZ2libGUiOmZhbHNlfSwicGF5dSI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJ0cnVzdGx5Ijp7ImVsaWdpYmxlIjpmYWxzZX0sImJsaWsiOnsiZWxpZ2libGUiOmZhbHNlfSwib3h4byI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJtYXhpbWEiOnsiZWxpZ2libGUiOmZhbHNlfSwiYm9sZXRvIjp7ImVsaWdpYmxlIjpmYWxzZX0sImNhcmQiOnsiZWxpZ2libGUiOnRydWUsImJyYW5kZWQiOnRydWUsInZlbmRvcnMiOnsidmlzYSI6eyJlbGlnaWJsZSI6dHJ1ZX0sIm1hc3RlcmNhcmQiOnsiZWxpZ2libGUiOnRydWV9LCJhbWV4Ijp7ImVsaWdpYmxlIjp0cnVlfSwiZGlzY292ZXIiOnsiZWxpZ2libGUiOmZhbHNlfSwiaGlwZXIiOnsiZWxpZ2libGUiOmZhbHNlfSwiZWxvIjp7ImVsaWdpYmxlIjpmYWxzZX0sImpjYiI6eyJlbGlnaWJsZSI6ZmFsc2V9fX19&platform=mobile&currency=EUR&intent=capture&commit=true (977)
> CordovaWebViewImpl: onPageDidNavigate(about:blank)
> CordovaWebViewImpl: onPageFinished(about:blank)
> ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
> CordovaActivity: Paused the activity.
> CordovaActivity: Stopped the activity.
> CordovaActivity: CordovaActivity.onDestroy()
> CordovaWebViewImpl: >>> loadUrl(about:blank)
> AwContents: WebView.destroy() called while WebView is still attached to window.token=
> cr_AwContents: Application attempted to call on a destroyed WebView
>     java.lang.Throwable
>         at org.chromium.android_webview.AwContents.a(PG:132)
>         at tD0.loadingStateChanged(PG:2)
>         at android.os.MessageQueue.nativePollOnce(Native Method)
>         at android.os.MessageQueue.next(MessageQueue.java:386)
>         at android.os.Looper.loop(Looper.java:175)
>         at android.app.ActivityThread.main(ActivityThread.java:7625)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
> 2019-10-30 11:28:50.929 22924-23008/it.extensione.bella D/ZrHung.AppEyeUiProbe: Current Activity:false
> 2019-10-30 11:28:50.929 22924-23008/it.extensione.bella D/ZrHung.AppEyeUiProbe: not watching, wait.
> ```


I believe too that something is changes on PaypalSDK, I think maybe Paypal is now forcing new "tab" on clicking in the button, and WebView is not getting js or something like that...

before this changes, PaypalSDK would open an Iframe on the same "tab"

Maybe there's a way to force this Iframe back, but no luck yet....
