### ISSUE TITLE
PayPalIntegrationType undefined on production

### ISSUE THREAD

**Issue by igorosabel** [Enngage/ngx-paypal#9]
Hi,

I already got everything tested and working on my localhost, but when I build for production using `ng build --prod` and I try it on the production site, it gives me this error:

`ERROR TypeError: Cannot read property 'ClientSideREST' of undefined`

Looks like `PayPalIntegrationType` is undefined. I managed to take a screenshot of the Chrome debugger.

Thanks.

![debugger](https://user-images.githubusercontent.com/633864/41564980-0c223f4e-7355-11e8-929a-4b3939a51eeb.png)

**Comment by Enngage** [comment]
I wasn't able to reproduce this, but I did switch to `ng-packgr` build format so I would recommend you to try this with latest version (`3.0.0`). I'm using production build on the [sample site](https://enngage.github.io/ngx-paypal/api) and seems to be working fine.

Let me know how that works.

**Comment by igorosabel** [comment]
Hi!

I've updated to `3.0.0` and now it works perfectly with `ng build --prod`

Thanks!!
