### ISSUE TITLE
Property 'purchase_units' does not exist on type 'IClientAuthorizeCallbackData'

### ISSUE THREAD

**Issue by guruputran** [Enngage/ngx-paypal#92]
Hi guys,

This issue happens when we use paypal response stream after onClientAuthorization
I used client-side authorization. Sandbox testing.
The data that I wanted to consume was:
purchase_units[0].amount.value and 
purchase_units[0].amount.currency_code

**Version used: 5.0.0**

I will provide the fix:
lib/models/paypal-model.d.ts

export interface IOrderDetails {
    create_time: string;
    update_time: string;
    id: string;
    intent: OrderIntent;
    payer: IPayer;
    status: OrderStatus;
    links: ILinkDescription[];
    **purchase_units: IPurchaseUnit[];** Add this in
}

Request the great originator of this package to kindly add this in next version.
Happy coding and thanks! Also you can close this issue.

**Comment by Enngage** [comment]
Hi,

Can you provide PR?

**Comment by guruputran** [comment]
Hi RS,
Done. Tq

**Comment by Enngage** [comment]
Hi, you need to submit PR in for this repo :) you only made change to your forked one.

**Comment by guruputran** [comment]
Did I do it rightly? :)

**Comment by Enngage** [comment]
Yes, just merged it :) thanks!
