### ISSUE TITLE
How to use intent=authorize

### ISSUE THREAD

**Issue by ollucks** [Enngage/ngx-paypal#96]
We need to create an order on our website with the option of collecting additional payments via the API at a later date, for circumstances where the order is altered after being placed.  

PayPal documentation suggests we need to create an order but using the intent=authorize to be able to collect additional payments.

Our integration using this plugin works fine when we use "intent: 'CAPTURE'" when creating the payPalConfig.  

If I change to "intent: 'AUTHORIZE'" then PayPal returns with " Error: Unexpected intent: AUTHORIZE passed to order.create. Please ensure you are passing /sdk/js?intent=authorize in the paypal script tag."

The paypal-models.d.ts shows 'CAPTURE' and 'AUTHORIZE' as allowed values so I'm assuming this plugin supports AUTHORISE but I can't find where to change the paypal script tag.

Does the plugin support AUTHORIZE and if so then how do we implement it?

**Comment by Enngage** [comment]
Hey,

You can pass custom params using the `advanced` configuration option when constructing paypal config object.

**Comment by ollucks** [comment]
Hi,

Thanks for the help.  I used this in my config and it's solved that problem :-)

advanced: {
    commit: 'true',
    extraQueryParams: [
        {
            name: 'intent',
            value: 'authorize'
        }
    ]
},
